/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  safelist: [
    'bg-surface',
    'dark:bg-surface-dark',
    'bg-bg-main',
    'bg-bg-section',
    'text-text-heading',
    'text-text-body',
    'text-text-muted',
    'font-heading',
    'grid-cols-1', 'grid-cols-2', 'grid-cols-3', 'grid-cols-4', 'grid-cols-5', 'grid-cols-6',
    'md:grid-cols-1', 'md:grid-cols-2', 'md:grid-cols-3', 'md:grid-cols-4', 'md:grid-cols-5', 'md:grid-cols-6',
    'lg:grid-cols-1', 'lg:grid-cols-2', 'lg:grid-cols-3', 'lg:grid-cols-4', 'lg:grid-cols-5', 'lg:grid-cols-6',
    'max-w-screen-xl', 'max-w-screen-2xl',
  ],
  theme: {
    container: {
      center: true,
      padding: { DEFAULT: '1rem', sm: '1.5rem' },
      screens: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px', '2xl': '1536px' },
    },
    extend: {
      colors: {
        primary: 'var(--color-primary, #2563EB)',
        'primary-hover': 'var(--color-primary-hover, #1D4ED8)',
        'primary-light': 'var(--color-primary-light, #DBEAFE)',
        'primary-500': 'var(--color-primary, #2563EB)',
        'primary-600': 'var(--color-primary-hover, #1D4ED8)',
        accent: 'var(--color-accent, #F97316)',
        'accent-hover': 'var(--color-accent-hover, #EA580C)',
        secondary: 'var(--color-dark, #0F172A)',
        'secondary-light': 'var(--color-dark-elevated, #1E293B)',
        'dark-elevated': 'var(--color-dark-elevated, #1E293B)',
        'bg-main': 'var(--color-bg, #F8FAFC)',
        'bg-card': 'var(--color-bg-card, #FFFFFF)',
        'bg-section': 'var(--color-bg-section, #F1F5F9)',
        'border-default': 'var(--color-border, #E2E8F0)',
        'text-heading': 'var(--color-text-heading, #0F172A)',
        'text-body': 'var(--color-text-body, #334155)',
        'text-muted': 'var(--color-text-secondary, #64748B)',
        success: 'var(--color-success, #16A34A)',
        'success-hover': '#15803D',
        warning: 'var(--color-warning, #F59E0B)',
        danger: 'var(--color-danger, #DC2626)',
        'danger-hover': '#B91C1C',
        'footer-bg': 'var(--color-footer-bg, #0F172A)',
        'footer-text': 'var(--color-footer-text, #94A3B8)',
        'footer-heading': 'var(--color-footer-heading, #CBD5F5)',
        // Legacy aliases → new system (no scattered hex)
        surface: 'var(--color-bg, #F8FAFC)',
        'surface-dark': 'var(--color-dark, #0F172A)',
        mint: 'var(--color-primary-light, #DBEAFE)',
        'edur-steel': 'var(--color-primary, #2563EB)',
        'edur-blue': 'var(--color-primary, #2563EB)',
        'edur-sky': 'var(--color-primary-light, #DBEAFE)',
        'edur-bg': 'var(--color-bg, #F8FAFC)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        heading: ['Manrope', 'Inter', 'system-ui', 'sans-serif'],
        urdu: ['"Noto Nastaliq Urdu"', 'Inter', 'serif'],
        arabic: ['"Noto Sans Arabic"', 'system-ui', 'sans-serif'],
      },
      letterSpacing: {
        tight: '-0.025em',
      },
      fontSize: {
        h1: ['2.25rem', { lineHeight: '1.2', fontWeight: '700' }],
        h2: ['1.875rem', { lineHeight: '1.3', fontWeight: '700' }],
        h3: ['1.5rem', { lineHeight: '1.35', fontWeight: '600' }],
        h4: ['1.25rem', { lineHeight: '1.4', fontWeight: '600' }],
        body: ['1rem', { lineHeight: '1.6' }],
        small: ['0.875rem', { lineHeight: '1.5' }],
        caption: ['0.75rem', { lineHeight: '1.4', fontWeight: '500' }],
      },
      boxShadow: {
        card: '0 4px 20px rgba(15, 23, 42, 0.05)',
        'card-hover': '0 10px 25px rgba(15, 23, 42, 0.08)',
        'btn-primary': '0 4px 12px rgba(37, 99, 235, 0.25)',
      },
      spacing: {
        18: '4.5rem',
        88: '22rem',
      },
      transitionDuration: {
        200: '200ms',
        250: '250ms',
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'reveal-up': {
          '0%': { opacity: '0', transform: 'translateY(28px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'reveal-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'dropdown-enter': {
          '0%': { opacity: '0', transform: 'translateY(-8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'drawer-enter': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'drawer-leave': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'overlay-enter': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'overlay-leave': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease-out',
        'fade-in-up': 'fade-in-up 0.35s ease-out',
        'reveal-up': 'reveal-up 0.6s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'reveal-in': 'reveal-in 0.5s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'dropdown-enter': 'dropdown-enter 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
        'drawer-enter': 'drawer-enter 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
        'drawer-leave': 'drawer-leave 0.2s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        'overlay-enter': 'overlay-enter 0.2s ease-out',
        'overlay-leave': 'overlay-leave 0.2s ease-out forwards',
      },
    },
  },
  plugins: [],
};
