import Stripe from 'stripe';import {MarketplacePaymentProvider} from './MarketplacePaymentProvider.js';
const unavailable=()=>Object.assign(new Error('Marketplace payment provider is not configured'),{status:503,code:'provider_not_configured'});
export function marketplaceStripeConfiguration(env=process.env){const mode=env.MARKETPLACE_STRIPE_MODE;if(!env.STRIPE_SECRET_KEY||!env.STRIPE_CONNECT_WEBHOOK_SECRET||!['test','live'].includes(mode))return'not_configured';if(mode==='live'&&env.MARKETPLACE_STRIPE_LIVE_ENABLED==='true')return'live_ready';if(mode==='test')return'test_ready';return'not_configured';}
export class StripeConnectProvider extends MarketplacePaymentProvider{constructor({client=null,env=process.env}={}){super();this.env=env;this.client=client;}configurationState(){return marketplaceStripeConfiguration(this.env);}stripe(){if(this.configurationState()==='not_configured')throw unavailable();if(!this.client)this.client=new Stripe(this.env.STRIPE_SECRET_KEY,{apiVersion:'2024-06-20'});return this.client;}
  async createConnectedAccount({country,metadata},idempotencyKey){const x=await this.stripe().accounts.create({type:'express',country,metadata,capabilities:{card_payments:{requested:true},transfers:{requested:true}}},{idempotencyKey});return{accountId:x.id};}
  async createOnboardingLink({accountId,refreshUrl,returnUrl}){const x=await this.stripe().accountLinks.create({account:accountId,refresh_url:refreshUrl,return_url:returnUrl,type:'account_onboarding'});return{url:x.url,expiresAt:x.expires_at};}
  async retrieveConnectedAccount(accountId){const x=await this.stripe().accounts.retrieve(accountId);return{accountId:x.id,detailsSubmitted:Boolean(x.details_submitted),chargesEnabled:Boolean(x.charges_enabled),payoutsEnabled:Boolean(x.payouts_enabled),chargesCapability:x.capabilities?.card_payments||'inactive',transfersCapability:x.capabilities?.transfers||'inactive',requirementsCurrent:x.requirements?.currently_due||[],requirementsPastDue:x.requirements?.past_due||[],disabledReason:x.requirements?.disabled_reason||'',country:x.country,currencies:x.default_currency?[String(x.default_currency).toUpperCase()]:[]};}
  async createPaymentIntent({amountMinor,currency,connectedAccountId,applicationFeeMinor,metadata},idempotencyKey){const x=await this.stripe().paymentIntents.create({amount:amountMinor,currency:currency.toLowerCase(),automatic_payment_methods:{enabled:true},application_fee_amount:applicationFeeMinor,transfer_data:{destination:connectedAccountId},metadata},{idempotencyKey});return{paymentIntentId:x.id,state:x.status,clientSecret:x.client_secret};}
  async retrievePaymentIntent(id){const x=await this.stripe().paymentIntents.retrieve(id);return{paymentIntentId:x.id,state:x.status,amountMinor:x.amount,currency:String(x.currency).toUpperCase(),destinationAccountId:x.transfer_data?.destination||x.transfer_data?.destination?.id,applicationFeeMinor:x.application_fee_amount||0,metadata:x.metadata||{}};}
  async createRefund({paymentIntentId,amountMinor,reverseTransfer=true,refundApplicationFee=true,metadata},idempotencyKey){const x=await this.stripe().refunds.create({payment_intent:paymentIntentId,amount:amountMinor,reverse_transfer:reverseTransfer,refund_application_fee:refundApplicationFee,metadata},{idempotencyKey});return{refundId:x.id,state:x.status,amountMinor:x.amount,currency:String(x.currency).toUpperCase()};}
  async retrieveRefund(id){const x=await this.stripe().refunds.retrieve(id);return{refundId:x.id,state:x.status,amountMinor:x.amount,currency:String(x.currency).toUpperCase(),paymentIntentId:x.payment_intent};}
  async retrievePayout(id,{accountId}){const x=await this.stripe().payouts.retrieve(id,{stripeAccount:accountId});return{payoutId:x.id,state:x.status,amountMinor:x.amount,currency:String(x.currency).toUpperCase()};}
  constructWebhookEvent(rawBody,signature){if(!Buffer.isBuffer(rawBody))throw Object.assign(new Error('Raw webhook body required'),{status:400,code:'raw_body_required'});if(!signature)throw Object.assign(new Error('Missing marketplace Stripe signature'),{status:400,code:'signature_missing'});return this.stripe().webhooks.constructEvent(rawBody,signature,this.env.STRIPE_CONNECT_WEBHOOK_SECRET);}
}
export const stripeConnectProvider=new StripeConnectProvider();
