export const ROUTES = {
  HOME: '/',
  JOBS: '/jobs',
  SCHOLARSHIPS: '/scholarships',
  ADMISSIONS: '/admissions',
  SCHOOLS_AND_COLLEGES: '/schools-and-colleges',
  FOREIGN_STUDIES: '/foreign-studies',
  BLOG: '/blog',
  CONTACT: '/contact',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  VERIFY_EMAIL: '/auth/verify-email',
  ACCEPT_INVITATION: '/auth/accept-invitation',
  PROFILE: '/profile',
  DASHBOARD: '/dashboard',
  SAVED_JOBS: '/saved-jobs',
  ADMIN: '/admin',
  RESUME_ANALYZER: '/resume-analyzer',
  EXAM_PREP: '/exam-prep',
  EXAM_DETAIL: '/exam-prep/:slug',
  QUIZ_TAKE: '/exam-prep/quiz/:quizId',
  INTERNSHIPS: '/internships',
  WEBINARS: '/webinars',
  INTL_SCHOLARSHIPS: '/intl-scholarships',
  BADGES_LEADERBOARD: '/badges',
  RESUME_BUILDER: '/resume-builder',
  CAREER_GUIDANCE: '/career-guidance',
  CAREER_ARTICLE: '/career-guidance/:slug',
  ABOUT: '/about',
  SERVICES: '/services',
  ADVERTISE: '/advertise',
  HELP_CENTER: '/help-center',
  FAQ: '/faq',
  SUBMIT_OPPORTUNITY: '/submit-opportunity',
  PRIVACY_POLICY: '/privacy-policy',
  TERMS: '/terms',
  COOKIES: '/cookies',
  LICENSE: '/license',
  DISCLAIMER: '/disclaimer',
  REFUND_POLICY: '/refund-policy',
  CAREERS: '/careers',
  SUPPORT: '/support',
  NOTIFICATIONS: '/notifications',
  FOREIGN_STUDY_DETAIL: '/foreign-studies/:slug',
  INSTITUTION_DETAIL: '/schools-and-colleges/:slug',
  EMPLOYER_LOGIN: '/employer/login',
  EMPLOYER_REGISTER: '/employer/register',
  EMPLOYER_DASHBOARD: '/employer',
  EMPLOYER_JOBS: '/employer/jobs',
  EMPLOYER_POST_JOB: '/employer/jobs/new',
  EMPLOYER_EDIT_JOB: '/employer/jobs/:jobId/edit',
  EMPLOYER_APPLICATIONS: '/employer/applications',
  EMPLOYER_ANALYTICS: '/employer/analytics',
  EMPLOYER_SETTINGS: '/employer/settings',
  EMPLOYER_NOTIFICATIONS: '/employer/notifications',
  EMPLOYER_INTELLIGENCE: '/employer/intelligence',
  EMPLOYER_INTELLIGENCE_CANDIDATES: '/employer/intelligence/candidates',
  EMPLOYER_INTELLIGENCE_COMPARE: '/employer/intelligence/compare',
  EMPLOYER_INTELLIGENCE_PIPELINE: '/employer/intelligence/pipeline',
  EMPLOYER_PUBLIC: '/employer',
  // Agent portal routes (Mission 11)
  AGENT_LOGIN: '/agent/login',
  AGENT_REGISTER: '/agent/register',
  AGENT_DASHBOARD: '/agent',
  AGENT_ONBOARDING: '/agent/onboarding',
  AGENT_PROFILE: '/agent/profile',
  AGENT_SERVICES: '/agent/services',
  AGENT_VERIFICATION: '/agent/verification',
  AGENT_TEAM: '/agent/team',
  AGENT_LEADS: '/agent/leads',
  AGENT_CLIENTS: '/agent/clients',
  AGENT_SETTINGS: '/agent/settings',
  AGENT_MARKETPLACE: '/agent/marketplace',
  AGENT_MARKETPLACE_NEW: '/agent/marketplace/new',
  AGENT_CONSULTATIONS: '/agent/consultations',
  AGENT_CASES: '/agent/cases',
  AGENT_AVAILABILITY: '/agent/availability',
  AGENT_PUBLIC_DIRECTORY: '/agents',
  AGENT_PUBLIC_PROFILE: '/agents/:slug',
  AGENT_PUBLIC_MARKETPLACE: '/agents/marketplace',
  AGENT_PUBLIC_MARKETPLACE_DETAIL: '/agents/marketplace/:slug',
  CONSULTATIONS: '/consultations',
  CASES: '/cases',
  CONSULTATION_REQUEST: '/consultations/new',
  CONSULTATION_DETAIL: '/consultations/:consultationId',
  COMPANY: '/company',
  UNIVERSITY: '/university',
  SEARCH: '/search',
  TALENT_PROFILE: '/talent-profile',
  APPLICATIONS: '/applications',
  APPLICATIONS_NEW: '/applications/new',
  ASSESSMENTS: '/assessments',
  ASSESSMENT_DETAIL: '/assessments/:slug',
  ASSESSMENT_TAKE: '/assessments/:slug/take',
  TEST_HUB: '/tests',
  TEST_DETAIL: '/tests/:slug',
  CANONICAL_SCHOLARSHIPS: '/scholarship-intelligence',
  CANONICAL_SCHOLARSHIP_DETAIL: '/scholarship-intelligence/:slug',
  PROGRAM_EXPLORER: '/program-explorer',
  PROGRAM_DETAIL: '/program-explorer/:slug',
  PERSONALIZATION_HUB: '/personalization',
  PERSONALIZATION_PROGRAM_ELIGIBILITY: '/personalization/programs/:programId/eligibility',
  PERSONALIZATION_SCHOLARSHIP_ELIGIBILITY: '/personalization/scholarships/:scholarshipId/eligibility',
  // Mission 9 — Action Engine / Journey Planner
  JOURNEY: '/journey',
  JOURNEY_TASKS: '/journey/tasks',
  JOURNEY_DEADLINES: '/journey/deadlines',
  JOURNEY_APPLICATIONS: '/journey/applications',
  JOURNEY_SAVED: '/journey/saved',
  // Mission 10 — Secure Document Vault
  VAULT: '/vault',
  VAULT_DOCUMENT: '/vault/:id',
};

export const ROLES = {
  USER: 'User',
  EDITOR: 'Editor',
  MODERATOR: 'Moderator',
  ADMIN: 'Admin',
  SUPER_ADMIN: 'SuperAdmin',
};

export const STAFF_ROLES = [ROLES.EDITOR, ROLES.MODERATOR, ROLES.ADMIN, ROLES.SUPER_ADMIN];

export const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
