import {
  AUTHORITY_TYPES,
  CATALOG_REVIEW_STATUSES,
  CATALOG_STATUSES,
  FACT_CATEGORIES,
  FEE_AMOUNT_MODELS,
  FEE_CADENCE,
  FEE_CATEGORIES,
  FRESHNESS_CLASSES,
  GBS_CATALOG_SCHEMA_VERSION,
  JURISDICTION_LEVELS,
  LAUNCH_COUNTRY_CODES,
  SOURCE_TYPES,
  STRUCTURAL_FUTURE_COUNTRY_CODES,
  US_LAUNCH_CANDIDATE_CODES,
} from '../catalogConstants.js';
import { FRESHNESS_POLICY, reviewIntervalDaysForClass } from '../freshnessPolicy.js';
import { validateJurisdictionGraph } from '../jurisdictionHierarchy.js';
import { assertLegalFactSourceAllowed } from '../officialSourcePolicy.js';
import { validateGovernmentFeeRecord } from '../governmentFeePolicy.js';
import { catalogFingerprintCanonical } from '../catalogFingerprint.js';
import { US_SUBNATIONAL } from './usSubnational.js';
import {
  CATALOG_CORRECTION_LAST_REVIEWED_AT,
  CATALOG_CORRECTION_RESEARCH_DATE,
  CATALOG_CORRECTION_RETRIEVED_AT,
  CATALOG_LAST_REVIEWED_AT,
  CATALOG_RESEARCH_DATE,
  CATALOG_RETRIEVED_AT,
  dueAtIso,
} from './researchMeta.js';

const SCHEMA = GBS_CATALOG_SCHEMA_VERSION;

function jid(code) {
  return `j:${code}`;
}

function reviewedMeta(freshnessClass, extra = {}) {
  const days = reviewIntervalDaysForClass(freshnessClass, FRESHNESS_POLICY);
  return {
    retrievedAt: CATALOG_RETRIEVED_AT,
    lastReviewedAt: CATALOG_LAST_REVIEWED_AT,
    reviewDueAt: dueAtIso(days),
    reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
    reviewedBy: 'staff:catalog_research_17d2',
    superseded: false,
    supersededBy: null,
    sourceVersion: 1,
    schemaVersion: SCHEMA,
    recordVersion: 0,
    freshnessClass,
    researchDate: CATALOG_RESEARCH_DATE,
    ...extra,
  };
}

function draftMeta(extra = {}) {
  return {
    retrievedAt: CATALOG_RETRIEVED_AT,
    lastReviewedAt: CATALOG_LAST_REVIEWED_AT,
    reviewDueAt: dueAtIso(reviewIntervalDaysForClass(FRESHNESS_CLASSES.SOURCE_DEFAULT)),
    reviewStatus: CATALOG_REVIEW_STATUSES.DRAFT,
    reviewedBy: null,
    superseded: false,
    supersededBy: null,
    sourceVersion: 1,
    schemaVersion: SCHEMA,
    recordVersion: 0,
    researchDate: CATALOG_RESEARCH_DATE,
    ...extra,
  };
}

function correctionReviewedMeta(freshnessClass, extra = {}) {
  const days = reviewIntervalDaysForClass(freshnessClass, FRESHNESS_POLICY);
  return {
    retrievedAt: CATALOG_CORRECTION_RETRIEVED_AT,
    lastReviewedAt: CATALOG_CORRECTION_LAST_REVIEWED_AT,
    reviewDueAt: dueAtIso(days, CATALOG_CORRECTION_LAST_REVIEWED_AT),
    reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
    reviewedBy: 'staff:catalog_research_17d2r1',
    superseded: false,
    supersededBy: null,
    sourceVersion: 1,
    schemaVersion: SCHEMA,
    recordVersion: 0,
    freshnessClass,
    researchDate: CATALOG_CORRECTION_RESEARCH_DATE,
    ...extra,
  };
}

export function buildCountryJurisdictions() {
  const launch = new Set(LAUNCH_COUNTRY_CODES);
  const names = {
    PK: 'Pakistan',
    US: 'United States',
    GB: 'United Kingdom',
    SG: 'Singapore',
    AE: 'United Arab Emirates',
    CA: 'Canada',
    AU: 'Australia',
  };
  const codes = [...LAUNCH_COUNTRY_CODES, ...STRUCTURAL_FUTURE_COUNTRY_CODES];
  return codes.map((code) => ({
    id: jid(code),
    code,
    countryCode: code,
    name: names[code],
    level: JURISDICTION_LEVELS.COUNTRY,
    parentJurisdictionId: null,
    status: CATALOG_STATUSES.ACTIVE,
    reviewStatus: CATALOG_REVIEW_STATUSES.DRAFT,
    launchCandidate: false,
    launchCoverage: launch.has(code),
    schemaVersion: SCHEMA,
    recordVersion: 0,
  }));
}

export function buildUsSubnationalJurisdictions() {
  const parent = jid('US');
  return US_SUBNATIONAL.map((row) => ({
    id: jid(`US-${row.code}`),
    code: row.code,
    countryCode: 'US',
    name: row.name,
    level: row.level,
    parentJurisdictionId: parent,
    status: CATALOG_STATUSES.ACTIVE,
    reviewStatus: CATALOG_REVIEW_STATUSES.DRAFT,
    launchCandidate: US_LAUNCH_CANDIDATE_CODES.includes(row.code),
    launchCoverage: false,
    schemaVersion: SCHEMA,
    recordVersion: 0,
  }));
}

export function buildAuthorities() {
  return [
    {
      authorityId: 'auth:PK-SECP',
      jurisdictionId: jid('PK'),
      authorityType: AUTHORITY_TYPES.NATIONAL_REGISTRAR,
      name: 'Securities and Exchange Commission of Pakistan',
      officialDomain: 'secp.gov.pk',
      canonicalUrl: 'https://www.secp.gov.pk/company-formation/registration-of-company/',
      status: CATALOG_STATUSES.ACTIVE,
      schemaVersion: SCHEMA,
      recordVersion: 0,
    },
    {
      authorityId: 'auth:PK-FBR',
      jurisdictionId: jid('PK'),
      authorityType: AUTHORITY_TYPES.TAX_AUTHORITY,
      name: 'Federal Board of Revenue',
      officialDomain: 'fbr.gov.pk',
      canonicalUrl: 'https://www.fbr.gov.pk/',
      status: CATALOG_STATUSES.ACTIVE,
      schemaVersion: SCHEMA,
      recordVersion: 0,
    },
    {
      authorityId: 'auth:GB-CH',
      jurisdictionId: jid('GB'),
      authorityType: AUTHORITY_TYPES.NATIONAL_REGISTRAR,
      name: 'Companies House',
      officialDomain: 'gov.uk',
      canonicalUrl: 'https://www.gov.uk/limited-company-formation/register-your-company',
      status: CATALOG_STATUSES.ACTIVE,
      schemaVersion: SCHEMA,
      recordVersion: 0,
    },
    {
      authorityId: 'auth:GB-HMRC',
      jurisdictionId: jid('GB'),
      authorityType: AUTHORITY_TYPES.TAX_AUTHORITY,
      name: 'HM Revenue and Customs',
      officialDomain: 'gov.uk',
      canonicalUrl: 'https://www.gov.uk/corporation-tax',
      status: CATALOG_STATUSES.ACTIVE,
      schemaVersion: SCHEMA,
      recordVersion: 0,
    },
    {
      authorityId: 'auth:US-IRS',
      jurisdictionId: jid('US'),
      authorityType: AUTHORITY_TYPES.TAX_AUTHORITY,
      name: 'Internal Revenue Service',
      officialDomain: 'irs.gov',
      canonicalUrl: 'https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online',
      status: CATALOG_STATUSES.ACTIVE,
      schemaVersion: SCHEMA,
      recordVersion: 0,
    },
    {
      authorityId: 'auth:US-DE-DOS',
      jurisdictionId: jid('US-DE'),
      authorityType: AUTHORITY_TYPES.STATE_REGISTRAR,
      name: 'Delaware Division of Corporations',
      officialDomain: 'corp.delaware.gov',
      canonicalUrl: 'https://corp.delaware.gov/howtoform/',
      status: CATALOG_STATUSES.ACTIVE,
      schemaVersion: SCHEMA,
      recordVersion: 0,
    },
    {
      authorityId: 'auth:US-WY-SOS',
      jurisdictionId: jid('US-WY'),
      authorityType: AUTHORITY_TYPES.STATE_REGISTRAR,
      name: 'Wyoming Secretary of State Business Division',
      officialDomain: 'sos.wyo.gov',
      canonicalUrl: 'https://sos.wyo.gov/business/default.aspx',
      status: CATALOG_STATUSES.ACTIVE,
      schemaVersion: SCHEMA,
      recordVersion: 0,
    },
    {
      authorityId: 'auth:US-FL-DOS',
      jurisdictionId: jid('US-FL'),
      authorityType: AUTHORITY_TYPES.STATE_REGISTRAR,
      name: 'Florida Division of Corporations',
      officialDomain: 'dos.fl.gov',
      canonicalUrl: 'https://dos.fl.gov/sunbiz/start-business/efile/fl-llc/',
      status: CATALOG_STATUSES.ACTIVE,
      schemaVersion: SCHEMA,
      recordVersion: 0,
    },
    {
      authorityId: 'auth:US-TX-SOS',
      jurisdictionId: jid('US-TX'),
      authorityType: AUTHORITY_TYPES.STATE_REGISTRAR,
      name: 'Texas Secretary of State',
      officialDomain: 'sos.texas.gov',
      canonicalUrl: 'https://www.sos.state.tx.us/corp/instructions/205.shtml',
      status: CATALOG_STATUSES.ACTIVE,
      schemaVersion: SCHEMA,
      recordVersion: 0,
    },
  ];
}

function source(row) {
  return {
    ...row,
    fingerprintCanonical: catalogFingerprintCanonical({
      sourceId: row.sourceId,
      authorityId: row.authorityId,
      jurisdictionId: row.jurisdictionId,
      sourceUrl: row.sourceUrl,
      sourceType: row.sourceType,
      factCategory: row.factCategory,
      title: row.title,
      sourceVersion: row.sourceVersion,
    }),
  };
}

export function buildSources() {
  return [
    source({
      sourceId: 'src:PK-SECP-registration',
      authorityId: 'auth:PK-SECP',
      jurisdictionId: jid('PK'),
      sourceUrl: 'https://www.secp.gov.pk/company-formation/registration-of-company/',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRAR,
      authorityType: AUTHORITY_TYPES.NATIONAL_REGISTRAR,
      factCategory: FACT_CATEGORIES.FORMATION_ELIGIBILITY,
      title: 'SECP registration of company',
      ...reviewedMeta(FRESHNESS_CLASSES.FORMATION_RULE),
    }),
    source({
      sourceId: 'src:PK-SECP-ezfile',
      authorityId: 'auth:PK-SECP',
      jurisdictionId: jid('PK'),
      sourceUrl: 'https://leap.secp.gov.pk/',
      sourceType: SOURCE_TYPES.GOVERNMENT_PORTAL,
      authorityType: AUTHORITY_TYPES.GOVERNMENT_BUSINESS_PORTAL,
      factCategory: FACT_CATEGORIES.FORMATION_STEP,
      title: 'SECP eZfile / LEAP portal',
      ...reviewedMeta(FRESHNESS_CLASSES.AUTHORITY_IDENTITY),
    }),
    source({
      sourceId: 'src:PK-FBR-home',
      authorityId: 'auth:PK-FBR',
      jurisdictionId: jid('PK'),
      sourceUrl: 'https://www.fbr.gov.pk/',
      sourceType: SOURCE_TYPES.OFFICIAL_TAX_AUTHORITY,
      authorityType: AUTHORITY_TYPES.TAX_AUTHORITY,
      factCategory: FACT_CATEGORIES.IDENTIFIER_TAX_REGISTRATION,
      title: 'FBR official site (tax authority distinct from SECP)',
      ...reviewedMeta(FRESHNESS_CLASSES.AUTHORITY_IDENTITY),
    }),
    source({
      sourceId: 'src:GB-CH-register',
      authorityId: 'auth:GB-CH',
      jurisdictionId: jid('GB'),
      sourceUrl: 'https://www.gov.uk/limited-company-formation/register-your-company',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRAR,
      authorityType: AUTHORITY_TYPES.NATIONAL_REGISTRAR,
      factCategory: FACT_CATEGORIES.GOVERNMENT_FEE,
      title: 'GOV.UK register your company (Companies House)',
      ...reviewedMeta(FRESHNESS_CLASSES.GOVERNMENT_FEE, { effectiveFrom: '2026-02-01T00:00:00.000Z' }),
    }),
    source({
      sourceId: 'src:GB-CH-fees',
      authorityId: 'auth:GB-CH',
      jurisdictionId: jid('GB'),
      sourceUrl: 'https://www.gov.uk/government/publications/companies-house-fees/companies-house-fees',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRAR,
      authorityType: AUTHORITY_TYPES.NATIONAL_REGISTRAR,
      factCategory: FACT_CATEGORIES.GOVERNMENT_FEE,
      title: 'Companies House fees (official publication)',
      ...reviewedMeta(FRESHNESS_CLASSES.GOVERNMENT_FEE, { effectiveFrom: '2026-02-01T00:00:00.000Z' }),
    }),
    source({
      sourceId: 'src:GB-CH-registered-office',
      authorityId: 'auth:GB-CH',
      jurisdictionId: jid('GB'),
      sourceUrl: 'https://www.gov.uk/limited-company-formation/company-address',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRAR,
      authorityType: AUTHORITY_TYPES.NATIONAL_REGISTRAR,
      factCategory: FACT_CATEGORIES.REGISTERED_OFFICE_REQUIREMENT,
      title: 'GOV.UK registered office and email address rules',
      ...reviewedMeta(FRESHNESS_CLASSES.FORMATION_RULE),
    }),
    source({
      sourceId: 'src:GB-CH-acsp',
      authorityId: 'auth:GB-CH',
      jurisdictionId: jid('GB'),
      sourceUrl: 'https://www.gov.uk/guidance/being-an-authorised-corporate-service-provider',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRAR,
      authorityType: AUTHORITY_TYPES.NATIONAL_REGISTRAR,
      factCategory: FACT_CATEGORIES.PROTECTED_TITLE_REFERENCE,
      title: 'Being an Authorised Corporate Service Provider (ACSP)',
      ...reviewedMeta(FRESHNESS_CLASSES.FORMATION_RULE),
    }),
    source({
      sourceId: 'src:GB-CH-acsp-list',
      authorityId: 'auth:GB-CH',
      jurisdictionId: jid('GB'),
      sourceUrl: 'https://www.gov.uk/government/publications/list-of-authorised-corporate-service-providers-acsps',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRY,
      authorityType: AUTHORITY_TYPES.OFFICIAL_REGISTRY,
      factCategory: FACT_CATEGORIES.PROTECTED_TITLE_REFERENCE,
      title: 'GOV.UK list of authorised corporate service providers (ACSPs)',
      ...correctionReviewedMeta(FRESHNESS_CLASSES.FORMATION_RULE, {
        notes: 'Official registry/list evidence class for ACSP. Partial/consent-based; not scraped in this phase.',
      }),
    }),
    source({
      sourceId: 'src:GB-CH-acsp-ceased',
      authorityId: 'auth:GB-CH',
      jurisdictionId: jid('GB'),
      sourceUrl: 'https://www.gov.uk/government/publications/ceased-or-suspended-authorised-corporate-service-providers-acsps',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRY,
      authorityType: AUTHORITY_TYPES.OFFICIAL_REGISTRY,
      factCategory: FACT_CATEGORIES.PROTECTED_TITLE_REFERENCE,
      title: 'GOV.UK ceased or suspended ACSPs',
      ...correctionReviewedMeta(FRESHNESS_CLASSES.FORMATION_RULE, {
        notes: 'Official ceased/suspended ACSP list. Status evidence class only; not scraped in this phase.',
      }),
    }),
    source({
      sourceId: 'src:GB-CH-search',
      authorityId: 'auth:GB-CH',
      jurisdictionId: jid('GB'),
      sourceUrl: 'https://find-and-update.company-information.service.gov.uk/',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRY,
      authorityType: AUTHORITY_TYPES.OFFICIAL_REGISTRY,
      factCategory: FACT_CATEGORIES.OFFICIAL_SEARCH,
      title: 'Companies House find and update company information',
      ...reviewedMeta(FRESHNESS_CLASSES.AUTHORITY_IDENTITY),
    }),
    source({
      sourceId: 'src:GB-HMRC-ct',
      authorityId: 'auth:GB-HMRC',
      jurisdictionId: jid('GB'),
      sourceUrl: 'https://www.gov.uk/corporation-tax',
      sourceType: SOURCE_TYPES.OFFICIAL_TAX_AUTHORITY,
      authorityType: AUTHORITY_TYPES.TAX_AUTHORITY,
      factCategory: FACT_CATEGORIES.IDENTIFIER_TAX_REGISTRATION,
      title: 'HMRC Corporation Tax (distinct from Companies House)',
      ...reviewedMeta(FRESHNESS_CLASSES.AUTHORITY_IDENTITY),
    }),
    source({
      sourceId: 'src:US-IRS-EIN',
      authorityId: 'auth:US-IRS',
      jurisdictionId: jid('US'),
      sourceUrl: 'https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online',
      sourceType: SOURCE_TYPES.OFFICIAL_TAX_AUTHORITY,
      authorityType: AUTHORITY_TYPES.TAX_AUTHORITY,
      factCategory: FACT_CATEGORIES.IDENTIFIER_TAX_REGISTRATION,
      title: 'IRS Apply for an EIN online',
      ...reviewedMeta(FRESHNESS_CLASSES.FORMATION_RULE, {
        notes: 'Process/identity source. 17D-2 retrieval did not state a government fee amount on this page.',
      }),
    }),
    source({
      sourceId: 'src:US-IRS-EIN-fee',
      authorityId: 'auth:US-IRS',
      jurisdictionId: jid('US'),
      sourceUrl: 'https://www.irs.gov/businesses/employer-identification-number',
      sourceType: SOURCE_TYPES.OFFICIAL_TAX_AUTHORITY,
      authorityType: AUTHORITY_TYPES.TAX_AUTHORITY,
      factCategory: FACT_CATEGORIES.GOVERNMENT_FEE,
      title: 'IRS Employer Identification Number (EIN) — apply free, direct from the IRS',
      ...correctionReviewedMeta(FRESHNESS_CLASSES.GOVERNMENT_FEE, {
        notes: 'Official IRS page states EIN issuance directly from the IRS is free. Provider EIN assistance remains a separate provider-defined fee. Does not guarantee issuance.',
      }),
    }),
    source({
      sourceId: 'src:US-DE-howtoform',
      authorityId: 'auth:US-DE-DOS',
      jurisdictionId: jid('US-DE'),
      sourceUrl: 'https://corp.delaware.gov/howtoform/',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRAR,
      authorityType: AUTHORITY_TYPES.STATE_REGISTRAR,
      factCategory: FACT_CATEGORIES.FORMATION_STEP,
      title: 'Delaware Division of Corporations how to form',
      ...reviewedMeta(FRESHNESS_CLASSES.AUTHORITY_IDENTITY),
    }),
    source({
      sourceId: 'src:US-DE-search',
      authorityId: 'auth:US-DE-DOS',
      jurisdictionId: jid('US-DE'),
      sourceUrl: 'https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRY,
      authorityType: AUTHORITY_TYPES.OFFICIAL_REGISTRY,
      factCategory: FACT_CATEGORIES.OFFICIAL_SEARCH,
      title: 'Delaware entity search',
      ...reviewedMeta(FRESHNESS_CLASSES.AUTHORITY_IDENTITY),
    }),
    source({
      sourceId: 'src:US-DE-fee-page',
      authorityId: 'auth:US-DE-DOS',
      jurisdictionId: jid('US-DE'),
      sourceUrl: 'https://corp.delaware.gov/fee/',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRAR,
      authorityType: AUTHORITY_TYPES.STATE_REGISTRAR,
      factCategory: FACT_CATEGORIES.GOVERNMENT_FEE,
      title: 'Delaware corporate fee schedule landing page (amount not catalogued in HTML)',
      ...draftMeta({
        freshnessClass: FRESHNESS_CLASSES.GOVERNMENT_FEE,
        superseded: true,
        supersededBy: 'src:US-DE-fee-schedule-2026-08',
        notes: '17D-2 historical source: HTML landing page does not publish a current LLC Certificate of Formation amount. Superseded as the fee-amount source by the official August 2026 fee schedule PDF. Record retained for provenance.',
      }),
    }),
    source({
      sourceId: 'src:US-DE-fee-schedule-2026-08',
      authorityId: 'auth:US-DE-DOS',
      jurisdictionId: jid('US-DE'),
      sourceUrl: 'https://corpfiles.delaware.gov/Fee_Schedule/AugustFee2026.pdf',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRAR,
      authorityType: AUTHORITY_TYPES.STATE_REGISTRAR,
      factCategory: FACT_CATEGORIES.GOVERNMENT_FEE,
      title: 'Delaware Division of Corporations fee schedule (revised August 2026)',
      ...correctionReviewedMeta(FRESHNESS_CLASSES.GOVERNMENT_FEE, {
        effectiveFrom: '2026-08-01T00:00:00.000Z',
        notes: 'Official PDF: Limited Liability Companies / Formation – domestic = $110.00. Revision observed August 2026.',
      }),
    }),
    source({
      sourceId: 'src:US-DE-ra',
      authorityId: 'auth:US-DE-DOS',
      jurisdictionId: jid('US-DE'),
      sourceUrl: 'https://corp.delaware.gov/faqs-regarding-registered-agents/',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRAR,
      authorityType: AUTHORITY_TYPES.STATE_REGISTRAR,
      factCategory: FACT_CATEGORIES.REGISTERED_AGENT_REQUIREMENT,
      title: 'Delaware FAQs regarding registered agents',
      ...correctionReviewedMeta(FRESHNESS_CLASSES.FORMATION_RULE, {
        notes: 'Every Delaware business entity must maintain a Registered Agent in Delaware with a physical street address. This is a formation requirement, not a government RA service price.',
      }),
    }),
    source({
      sourceId: 'src:US-WY-sos',
      authorityId: 'auth:US-WY-SOS',
      jurisdictionId: jid('US-WY'),
      sourceUrl: 'https://sos.wyo.gov/business/default.aspx',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRAR,
      authorityType: AUTHORITY_TYPES.STATE_REGISTRAR,
      factCategory: FACT_CATEGORIES.FORMATION_STEP,
      title: 'Wyoming SOS Business & UCC Center',
      ...reviewedMeta(FRESHNESS_CLASSES.AUTHORITY_IDENTITY),
    }),
    source({
      sourceId: 'src:US-WY-fees',
      authorityId: 'auth:US-WY-SOS',
      jurisdictionId: jid('US-WY'),
      sourceUrl: 'https://sos.wyo.gov/Business/docs/BusinessFees.pdf',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRAR,
      authorityType: AUTHORITY_TYPES.STATE_REGISTRAR,
      factCategory: FACT_CATEGORIES.GOVERNMENT_FEE,
      title: 'Wyoming Business Division filing fee schedule (effective 1 Jul 2026)',
      ...reviewedMeta(FRESHNESS_CLASSES.GOVERNMENT_FEE, { effectiveFrom: '2026-07-01T00:00:00.000Z' }),
    }),
    source({
      sourceId: 'src:US-WY-ra',
      authorityId: 'auth:US-WY-SOS',
      jurisdictionId: jid('US-WY'),
      sourceUrl: 'https://sos.wyo.gov/Business/docs/HowToFindOrBecomeARegisteredAgent.pdf',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRAR,
      authorityType: AUTHORITY_TYPES.STATE_REGISTRAR,
      factCategory: FACT_CATEGORIES.REGISTERED_AGENT_REQUIREMENT,
      title: 'Wyoming how to find or become a registered agent',
      ...reviewedMeta(FRESHNESS_CLASSES.FORMATION_RULE),
    }),
    source({
      sourceId: 'src:US-WY-search',
      authorityId: 'auth:US-WY-SOS',
      jurisdictionId: jid('US-WY'),
      sourceUrl: 'https://wyobiz.wyo.gov/',
      sourceType: SOURCE_TYPES.GOVERNMENT_PORTAL,
      authorityType: AUTHORITY_TYPES.GOVERNMENT_BUSINESS_PORTAL,
      factCategory: FACT_CATEGORIES.OFFICIAL_SEARCH,
      title: 'WyoBiz online business services',
      ...reviewedMeta(FRESHNESS_CLASSES.AUTHORITY_IDENTITY),
    }),
    source({
      sourceId: 'src:US-FL-efile',
      authorityId: 'auth:US-FL-DOS',
      jurisdictionId: jid('US-FL'),
      sourceUrl: 'https://dos.fl.gov/sunbiz/start-business/efile/fl-llc/',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRAR,
      authorityType: AUTHORITY_TYPES.STATE_REGISTRAR,
      factCategory: FACT_CATEGORIES.FORMATION_STEP,
      title: 'Florida LLC articles of organization e-file',
      ...reviewedMeta(FRESHNESS_CLASSES.FORMATION_RULE),
    }),
    source({
      sourceId: 'src:US-FL-llc-fees',
      authorityId: 'auth:US-FL-DOS',
      jurisdictionId: jid('US-FL'),
      sourceUrl: 'https://dos.fl.gov/sunbiz/forms/fees/llc-fees',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRAR,
      authorityType: AUTHORITY_TYPES.STATE_REGISTRAR,
      factCategory: FACT_CATEGORIES.GOVERNMENT_FEE,
      title: 'Florida Division of Corporations LLC fees',
      ...reviewedMeta(FRESHNESS_CLASSES.GOVERNMENT_FEE),
    }),
    source({
      sourceId: 'src:US-FL-search',
      authorityId: 'auth:US-FL-DOS',
      jurisdictionId: jid('US-FL'),
      sourceUrl: 'https://search.sunbiz.org/Inquiry/CorporationSearch/ByName',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRY,
      authorityType: AUTHORITY_TYPES.OFFICIAL_REGISTRY,
      factCategory: FACT_CATEGORIES.OFFICIAL_SEARCH,
      title: 'Sunbiz entity search',
      ...reviewedMeta(FRESHNESS_CLASSES.AUTHORITY_IDENTITY),
    }),
    source({
      sourceId: 'src:US-TX-form205',
      authorityId: 'auth:US-TX-SOS',
      jurisdictionId: jid('US-TX'),
      sourceUrl: 'https://www.sos.state.tx.us/corp/instructions/205.shtml',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRAR,
      authorityType: AUTHORITY_TYPES.STATE_REGISTRAR,
      factCategory: FACT_CATEGORIES.GOVERNMENT_FEE,
      title: 'Texas Form 205 Certificate of Formation — LLC instructions',
      ...reviewedMeta(FRESHNESS_CLASSES.GOVERNMENT_FEE),
    }),
    source({
      sourceId: 'src:US-TX-fee-schedule',
      authorityId: 'auth:US-TX-SOS',
      jurisdictionId: jid('US-TX'),
      sourceUrl: 'https://direct.sos.state.tx.us/help/help-corp.asp?pg=fee',
      sourceType: SOURCE_TYPES.OFFICIAL_REGISTRAR,
      authorityType: AUTHORITY_TYPES.STATE_REGISTRAR,
      factCategory: FACT_CATEGORIES.GOVERNMENT_FEE,
      title: 'Texas SOS business filings fee schedule',
      ...reviewedMeta(FRESHNESS_CLASSES.GOVERNMENT_FEE),
    }),
    source({
      sourceId: 'src:US-TX-search',
      authorityId: 'auth:US-TX-SOS',
      jurisdictionId: jid('US-TX'),
      sourceUrl: 'https://direct.sos.state.tx.us/',
      sourceType: SOURCE_TYPES.GOVERNMENT_PORTAL,
      authorityType: AUTHORITY_TYPES.GOVERNMENT_BUSINESS_PORTAL,
      factCategory: FACT_CATEGORIES.OFFICIAL_SEARCH,
      title: 'Texas SOSDirect',
      ...reviewedMeta(FRESHNESS_CLASSES.AUTHORITY_IDENTITY),
    }),
  ];
}

export function buildEntityTypes() {
  const common = {
    status: CATALOG_STATUSES.ACTIVE,
    schemaVersion: SCHEMA,
    recordVersion: 0,
  };
  return [
    {
      entityTypeId: 'et:PK:PVT',
      jurisdictionId: jid('PK'),
      code: 'PVT',
      displayName: 'Private company',
      officialName: 'Private company limited by shares',
      sourceId: 'src:PK-SECP-registration',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      ...common,
    },
    {
      entityTypeId: 'et:PK:SMC',
      jurisdictionId: jid('PK'),
      code: 'SMC',
      displayName: 'Single Member Company',
      officialName: 'Single member company',
      sourceId: 'src:PK-SECP-registration',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      ...common,
    },
    {
      entityTypeId: 'et:GB:LTD',
      jurisdictionId: jid('GB'),
      code: 'LTD',
      displayName: 'Private limited company',
      officialName: 'Private company limited by shares',
      sourceId: 'src:GB-CH-register',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      ...common,
    },
    {
      entityTypeId: 'et:US-DE:LLC',
      jurisdictionId: jid('US-DE'),
      code: 'LLC',
      displayName: 'Delaware LLC',
      officialName: 'Limited Liability Company',
      sourceId: 'src:US-DE-howtoform',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      ...common,
    },
    {
      entityTypeId: 'et:US-WY:LLC',
      jurisdictionId: jid('US-WY'),
      code: 'LLC',
      displayName: 'Wyoming LLC',
      officialName: 'Limited Liability Company',
      sourceId: 'src:US-WY-sos',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      ...common,
    },
    {
      entityTypeId: 'et:US-FL:LLC',
      jurisdictionId: jid('US-FL'),
      code: 'LLC',
      displayName: 'Florida LLC',
      officialName: 'Florida Limited Liability Company',
      sourceId: 'src:US-FL-efile',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      ...common,
    },
    {
      entityTypeId: 'et:US-TX:LLC',
      jurisdictionId: jid('US-TX'),
      code: 'LLC',
      displayName: 'Texas LLC',
      officialName: 'Limited Liability Company',
      sourceId: 'src:US-TX-form205',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      ...common,
    },
  ];
}

function fee(row) {
  return {
    ownership: 'government',
    fxAuthoritative: false,
    schemaVersion: SCHEMA,
    recordVersion: 0,
    ...row,
  };
}

export function buildFees() {
  return [
    fee({
      feeId: 'fee:GB-CH-incorporation-online',
      jurisdictionId: jid('GB'),
      authorityId: 'auth:GB-CH',
      entityTypeId: 'et:GB:LTD',
      feeCategory: FEE_CATEGORIES.FORMATION_FILING,
      label: 'Companies House digital incorporation',
      currency: 'GBP',
      amountModel: FEE_AMOUNT_MODELS.FIXED,
      amount: 100,
      required: true,
      cadence: FEE_CADENCE.ONE_TIME,
      effectiveFrom: '2026-02-01T00:00:00.000Z',
      effectiveTo: null,
      sourceId: 'src:GB-CH-fees',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(90),
    }),
    fee({
      feeId: 'fee:GB-CH-incorporation-paper',
      jurisdictionId: jid('GB'),
      authorityId: 'auth:GB-CH',
      entityTypeId: 'et:GB:LTD',
      feeCategory: FEE_CATEGORIES.FORMATION_FILING,
      label: 'Companies House paper incorporation',
      currency: 'GBP',
      amountModel: FEE_AMOUNT_MODELS.FIXED,
      amount: 124,
      required: true,
      cadence: FEE_CADENCE.ONE_TIME,
      effectiveFrom: '2026-02-01T00:00:00.000Z',
      effectiveTo: null,
      sourceId: 'src:GB-CH-fees',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(90),
    }),
    fee({
      feeId: 'fee:GB-CH-confirmation-statement-digital',
      jurisdictionId: jid('GB'),
      authorityId: 'auth:GB-CH',
      entityTypeId: 'et:GB:LTD',
      feeCategory: FEE_CATEGORIES.PERIODIC_REPORT,
      label: 'Companies House digital confirmation statement',
      currency: 'GBP',
      amountModel: FEE_AMOUNT_MODELS.FIXED,
      amount: 50,
      required: true,
      cadence: FEE_CADENCE.RECURRING,
      effectiveFrom: '2026-02-01T00:00:00.000Z',
      effectiveTo: null,
      sourceId: 'src:GB-CH-fees',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(90),
    }),
    fee({
      feeId: 'fee:US-WY-llc-articles',
      jurisdictionId: jid('US-WY'),
      authorityId: 'auth:US-WY-SOS',
      entityTypeId: 'et:US-WY:LLC',
      feeCategory: FEE_CATEGORIES.FORMATION_FILING,
      label: 'Wyoming LLC Articles of Organization / Continuance / Domestication',
      currency: 'USD',
      amountModel: FEE_AMOUNT_MODELS.FIXED,
      amount: 100,
      required: true,
      cadence: FEE_CADENCE.ONE_TIME,
      effectiveFrom: '2026-07-01T00:00:00.000Z',
      effectiveTo: null,
      sourceId: 'src:US-WY-fees',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(90),
    }),
    fee({
      feeId: 'fee:US-FL-llc-articles',
      jurisdictionId: jid('US-FL'),
      authorityId: 'auth:US-FL-DOS',
      entityTypeId: 'et:US-FL:LLC',
      feeCategory: FEE_CATEGORIES.FORMATION_FILING,
      label: 'Florida LLC Articles of Organization filing fee',
      currency: 'USD',
      amountModel: FEE_AMOUNT_MODELS.FIXED,
      amount: 100,
      required: true,
      cadence: FEE_CADENCE.ONE_TIME,
      effectiveFrom: null,
      effectiveTo: null,
      sourceId: 'src:US-FL-llc-fees',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(90),
    }),
    fee({
      feeId: 'fee:US-FL-llc-ra-designation',
      jurisdictionId: jid('US-FL'),
      authorityId: 'auth:US-FL-DOS',
      entityTypeId: 'et:US-FL:LLC',
      feeCategory: FEE_CATEGORIES.REGISTERED_AGENT_DESIGNATION,
      label: 'Florida LLC registered agent designation fee',
      currency: 'USD',
      amountModel: FEE_AMOUNT_MODELS.FIXED,
      amount: 25,
      required: true,
      cadence: FEE_CADENCE.ONE_TIME,
      effectiveFrom: null,
      effectiveTo: null,
      sourceId: 'src:US-FL-llc-fees',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(90),
    }),
    fee({
      feeId: 'fee:US-TX-llc-formation',
      jurisdictionId: jid('US-TX'),
      authorityId: 'auth:US-TX-SOS',
      entityTypeId: 'et:US-TX:LLC',
      feeCategory: FEE_CATEGORIES.FORMATION_FILING,
      label: 'Texas Certificate of Formation for an LLC (Form 205)',
      currency: 'USD',
      amountModel: FEE_AMOUNT_MODELS.FIXED,
      amount: 300,
      required: true,
      cadence: FEE_CADENCE.ONE_TIME,
      effectiveFrom: null,
      effectiveTo: null,
      sourceId: 'src:US-TX-form205',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(90),
    }),
    fee({
      feeId: 'fee:US-DE-llc-formation',
      jurisdictionId: jid('US-DE'),
      authorityId: 'auth:US-DE-DOS',
      entityTypeId: 'et:US-DE:LLC',
      feeCategory: FEE_CATEGORIES.FORMATION_FILING,
      label: 'Delaware LLC Certificate of Formation',
      currency: 'USD',
      amountModel: FEE_AMOUNT_MODELS.NOT_CATALOGUED,
      amount: null,
      required: true,
      cadence: FEE_CADENCE.ONE_TIME,
      effectiveFrom: null,
      effectiveTo: null,
      sourceId: 'src:US-DE-fee-page',
      sourceVersion: 1,
      recordVersion: 0,
      reviewStatus: CATALOG_REVIEW_STATUSES.SUPERSEDED,
      superseded: true,
      supersededBy: 'fee:US-DE-llc-formation::2',
      reviewDueAt: dueAtIso(90),
      lastReviewedAt: CATALOG_LAST_REVIEWED_AT,
      retrievedAt: CATALOG_RETRIEVED_AT,
      notes: '17D-2 historical: official HTML fee landing page did not state a current LLC formation amount; left not_catalogued. Retained for provenance after 17D-2R1 PDF correction.',
    }),
    fee({
      feeId: 'fee:US-DE-llc-formation',
      jurisdictionId: jid('US-DE'),
      authorityId: 'auth:US-DE-DOS',
      entityTypeId: 'et:US-DE:LLC',
      feeCategory: FEE_CATEGORIES.FORMATION_FILING,
      label: 'Delaware LLC Certificate of Formation (domestic)',
      currency: 'USD',
      amountModel: FEE_AMOUNT_MODELS.FIXED,
      amount: 110,
      required: true,
      cadence: FEE_CADENCE.ONE_TIME,
      effectiveFrom: '2026-08-01T00:00:00.000Z',
      effectiveTo: null,
      sourceId: 'src:US-DE-fee-schedule-2026-08',
      sourceVersion: 2,
      recordVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(90, CATALOG_CORRECTION_LAST_REVIEWED_AT),
      lastReviewedAt: CATALOG_CORRECTION_LAST_REVIEWED_AT,
      retrievedAt: CATALOG_CORRECTION_RETRIEVED_AT,
      notes: 'Government fee from Delaware Division of Corporations official fee schedule revised August 2026: Formation – domestic LLC = USD 110. Not a provider Registered Agent price.',
    }),
    fee({
      feeId: 'fee:PK-SECP-incorporation',
      jurisdictionId: jid('PK'),
      authorityId: 'auth:PK-SECP',
      entityTypeId: 'et:PK:PVT',
      feeCategory: FEE_CATEGORIES.FORMATION_FILING,
      label: 'SECP company incorporation fee',
      currency: 'PKR',
      amountModel: FEE_AMOUNT_MODELS.NOT_CATALOGUED,
      amount: null,
      required: true,
      cadence: FEE_CADENCE.ONE_TIME,
      effectiveFrom: null,
      effectiveTo: null,
      sourceId: 'src:PK-SECP-registration',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.DRAFT,
      reviewDueAt: dueAtIso(90),
      notes: 'SECP official pages were not fully accessible for fee extraction in this research window; amount left not_catalogued.',
    }),
    fee({
      feeId: 'fee:US-IRS-EIN',
      jurisdictionId: jid('US'),
      authorityId: 'auth:US-IRS',
      entityTypeId: null,
      feeCategory: FEE_CATEGORIES.OTHER_GOVERNMENT,
      label: 'IRS EIN application',
      currency: 'USD',
      amountModel: FEE_AMOUNT_MODELS.NOT_CATALOGUED,
      amount: null,
      required: false,
      cadence: FEE_CADENCE.ONE_TIME,
      effectiveFrom: null,
      effectiveTo: null,
      sourceId: 'src:US-IRS-EIN',
      sourceVersion: 1,
      recordVersion: 0,
      reviewStatus: CATALOG_REVIEW_STATUSES.SUPERSEDED,
      superseded: true,
      supersededBy: 'fee:US-IRS-EIN::2',
      reviewDueAt: dueAtIso(90),
      lastReviewedAt: CATALOG_LAST_REVIEWED_AT,
      retrievedAt: CATALOG_RETRIEVED_AT,
      notes: '17D-2 historical: IRS apply-online page retrieved did not state a filing amount; left not_catalogued. Retained for provenance after 17D-2R1 official EIN fee correction.',
    }),
    fee({
      feeId: 'fee:US-IRS-EIN',
      jurisdictionId: jid('US'),
      authorityId: 'auth:US-IRS',
      entityTypeId: null,
      feeCategory: FEE_CATEGORIES.EIN_ISSUANCE,
      label: 'IRS EIN application / issuance',
      currency: 'USD',
      amountModel: FEE_AMOUNT_MODELS.FIXED,
      amount: 0,
      required: false,
      cadence: FEE_CADENCE.ONE_TIME,
      effectiveFrom: null,
      effectiveTo: null,
      sourceId: 'src:US-IRS-EIN-fee',
      sourceVersion: 2,
      recordVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(90, CATALOG_CORRECTION_LAST_REVIEWED_AT),
      lastReviewedAt: CATALOG_CORRECTION_LAST_REVIEWED_AT,
      retrievedAt: CATALOG_CORRECTION_RETRIEVED_AT,
      notes: 'IRS government fee is USD 0 when issued directly by the IRS. Provider EIN assistance remains a separate provider-defined fee and is not catalogued here. Does not guarantee EIN issuance. Form the state entity first remains a separate rule.',
    }),
  ];
}

export function buildRules() {
  const base = {
    schemaVersion: SCHEMA,
    recordVersion: 0,
    superseded: false,
  };
  return [
    {
      ruleId: 'rule:PK-private-company-members',
      jurisdictionId: jid('PK'),
      authorityId: 'auth:PK-SECP',
      entityTypeId: 'et:PK:PVT',
      factCategory: FACT_CATEGORIES.DIRECTOR_MEMBER_SHAREHOLDER_RULE,
      payload: { minMembers: 2, maxMembers: 50, notes: 'SECP: any two or more persons may form a private company; FAQ states maximum members should not be more than 50.' },
      sourceId: 'src:PK-SECP-registration',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(180),
      effectiveFrom: null,
      effectiveTo: null,
      ...base,
    },
    {
      ruleId: 'rule:PK-smc-one-member',
      jurisdictionId: jid('PK'),
      authorityId: 'auth:PK-SECP',
      entityTypeId: 'et:PK:SMC',
      factCategory: FACT_CATEGORIES.FORMATION_ELIGIBILITY,
      payload: { minMembers: 1, maxMembers: 1, notes: 'If only one member forms a private company, it is a single member company.' },
      sourceId: 'src:PK-SECP-registration',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(180),
      effectiveFrom: null,
      effectiveTo: null,
      ...base,
    },
    {
      ruleId: 'rule:PK-secp-not-fbr',
      jurisdictionId: jid('PK'),
      authorityId: 'auth:PK-SECP',
      entityTypeId: null,
      factCategory: FACT_CATEGORIES.IDENTIFIER_TAX_REGISTRATION,
      payload: {
        secpIncorporationDoesNotCompleteNtn: true,
        bankAccountNotGuaranteed: true,
        taxRegistrationNotGuaranteed: true,
      },
      sourceId: 'src:PK-FBR-home',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(180),
      effectiveFrom: null,
      effectiveTo: null,
      ...base,
    },
    {
      ruleId: 'rule:GB-registered-office',
      jurisdictionId: jid('GB'),
      authorityId: 'auth:GB-CH',
      entityTypeId: 'et:GB:LTD',
      factCategory: FACT_CATEGORIES.REGISTERED_OFFICE_REQUIREMENT,
      payload: {
        physicalUkAddressRequired: true,
        poBoxNotPermitted: true,
        mustMatchRegistrationCountry: true,
      },
      sourceId: 'src:GB-CH-registered-office',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(180),
      effectiveFrom: null,
      effectiveTo: null,
      ...base,
    },
    {
      ruleId: 'rule:GB-acsp-protected',
      jurisdictionId: jid('GB'),
      authorityId: 'auth:GB-CH',
      entityTypeId: null,
      factCategory: FACT_CATEGORIES.PROTECTED_TITLE_REFERENCE,
      payload: {
        acspIsProtectedTitle: true,
        ordinaryAgentVerificationDoesNotGrantAcsp: true,
      },
      sourceId: 'src:GB-CH-acsp',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(180),
      effectiveFrom: null,
      effectiveTo: null,
      ...base,
    },
    {
      ruleId: 'rule:GB-ch-not-hmrc',
      jurisdictionId: jid('GB'),
      authorityId: 'auth:GB-CH',
      entityTypeId: 'et:GB:LTD',
      factCategory: FACT_CATEGORIES.IDENTIFIER_TAX_REGISTRATION,
      payload: { companiesHouseIsNotHmrc: true, corporationTaxIsHmrc: true },
      sourceId: 'src:GB-HMRC-ct',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(180),
      effectiveFrom: null,
      effectiveTo: null,
      ...base,
    },
    {
      ruleId: 'rule:US-IRS-ein-after-state',
      jurisdictionId: jid('US'),
      authorityId: 'auth:US-IRS',
      entityTypeId: null,
      factCategory: FACT_CATEGORIES.IDENTIFIER_TAX_REGISTRATION,
      payload: {
        formStateEntityBeforeEin: true,
        einIsFederalNotStateFormation: true,
        instantEinNotClaimed: true,
      },
      sourceId: 'src:US-IRS-EIN',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(180),
      effectiveFrom: null,
      effectiveTo: null,
      ...base,
    },
    {
      ruleId: 'rule:US-WY-registered-agent',
      jurisdictionId: jid('US-WY'),
      authorityId: 'auth:US-WY-SOS',
      entityTypeId: 'et:US-WY:LLC',
      factCategory: FACT_CATEGORIES.REGISTERED_AGENT_REQUIREMENT,
      payload: {
        required: true,
        physicalWyomingAddressRequired: true,
        poBoxInsufficient: true,
        dropBoxNotAcceptable: true,
      },
      sourceId: 'src:US-WY-ra',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(180),
      effectiveFrom: null,
      effectiveTo: null,
      ...base,
    },
    {
      ruleId: 'rule:US-FL-llc-supported',
      jurisdictionId: jid('US-FL'),
      authorityId: 'auth:US-FL-DOS',
      entityTypeId: 'et:US-FL:LLC',
      factCategory: FACT_CATEGORIES.FORMATION_ELIGIBILITY,
      payload: { llcSupported: true, registeredAgentDesignationFeeSeparate: true },
      sourceId: 'src:US-FL-efile',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(180),
      effectiveFrom: null,
      effectiveTo: null,
      ...base,
    },
    {
      ruleId: 'rule:US-TX-registered-agent',
      jurisdictionId: jid('US-TX'),
      authorityId: 'auth:US-TX-SOS',
      entityTypeId: 'et:US-TX:LLC',
      factCategory: FACT_CATEGORIES.REGISTERED_AGENT_REQUIREMENT,
      payload: {
        required: true,
        entityCannotActAsOwnAgent: true,
        registeredOfficeNotMailboxOnly: true,
      },
      sourceId: 'src:US-TX-form205',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(180),
      effectiveFrom: null,
      effectiveTo: null,
      ...base,
    },
    {
      ruleId: 'rule:US-DE-llc-supported',
      jurisdictionId: jid('US-DE'),
      authorityId: 'auth:US-DE-DOS',
      entityTypeId: 'et:US-DE:LLC',
      factCategory: FACT_CATEGORIES.FORMATION_ELIGIBILITY,
      payload: { llcSupported: true, formationFeeNotCatalogued: true },
      sourceId: 'src:US-DE-howtoform',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.SUPERSEDED,
      superseded: true,
      supersededBy: 'rule:US-DE-llc-supported::2',
      reviewDueAt: dueAtIso(180),
      effectiveFrom: null,
      effectiveTo: null,
      ...base,
    },
    {
      ruleId: 'rule:US-DE-llc-supported',
      jurisdictionId: jid('US-DE'),
      authorityId: 'auth:US-DE-DOS',
      entityTypeId: 'et:US-DE:LLC',
      factCategory: FACT_CATEGORIES.FORMATION_ELIGIBILITY,
      payload: { llcSupported: true, formationFeeNotCatalogued: false },
      sourceId: 'src:US-DE-howtoform',
      sourceVersion: 2,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(180, CATALOG_CORRECTION_LAST_REVIEWED_AT),
      lastReviewedAt: CATALOG_CORRECTION_LAST_REVIEWED_AT,
      retrievedAt: CATALOG_CORRECTION_RETRIEVED_AT,
      effectiveFrom: null,
      effectiveTo: null,
      ...base,
    },
    {
      ruleId: 'rule:US-DE-registered-agent',
      jurisdictionId: jid('US-DE'),
      authorityId: 'auth:US-DE-DOS',
      entityTypeId: 'et:US-DE:LLC',
      factCategory: FACT_CATEGORIES.REGISTERED_AGENT_REQUIREMENT,
      payload: {
        required: true,
        physicalDelawareStreetAddressRequired: true,
        poBoxInsufficient: true,
        governmentRegisteredAgentServiceFeeNotCatalogued: true,
        providerRegisteredAgentPriceNotInvented: true,
      },
      sourceId: 'src:US-DE-ra',
      sourceVersion: 1,
      reviewStatus: CATALOG_REVIEW_STATUSES.REVIEWED,
      reviewDueAt: dueAtIso(180, CATALOG_CORRECTION_LAST_REVIEWED_AT),
      lastReviewedAt: CATALOG_CORRECTION_LAST_REVIEWED_AT,
      retrievedAt: CATALOG_CORRECTION_RETRIEVED_AT,
      effectiveFrom: null,
      effectiveTo: null,
      ...base,
    },
  ];
}

export function loadGbsCatalogManifest() {
  const jurisdictions = [...buildCountryJurisdictions(), ...buildUsSubnationalJurisdictions()];
  const graph = validateJurisdictionGraph(jurisdictions);
  if (!graph.ok) {
    throw new Error(`GBS catalog jurisdiction graph invalid: ${graph.errors.join('; ')}`);
  }
  const authorities = buildAuthorities();
  const sources = buildSources();
  const entityTypes = buildEntityTypes();
  const fees = buildFees();
  const rules = buildRules();

  const authorityById = new Map(authorities.map((a) => [a.authorityId, a]));
  const jurisdictionIds = new Set(jurisdictions.map((j) => j.id));
  const entityTypeIds = new Set(entityTypes.map((e) => e.entityTypeId));

  for (const src of sources) {
    const authority = authorityById.get(src.authorityId);
    const allowed = assertLegalFactSourceAllowed({
      ...src,
      expectedAuthorityId: src.authorityId,
      expectedJurisdictionId: src.jurisdictionId,
    });
    if (!allowed.ok) {
      throw new Error(`catalog source ${src.sourceId}: ${allowed.errors.join('; ')}`);
    }
    if (!authority) throw new Error(`catalog source ${src.sourceId} unknown authority`);
    if (authority.jurisdictionId !== src.jurisdictionId) {
      throw new Error(`catalog source ${src.sourceId} authority/jurisdiction bind mismatch`);
    }
    if (!jurisdictionIds.has(src.jurisdictionId)) {
      throw new Error(`catalog source ${src.sourceId} unknown jurisdiction`);
    }
  }

  for (const feeRow of fees) {
    const parsed = validateGovernmentFeeRecord(feeRow);
    if (!parsed.ok) throw new Error(`catalog fee ${feeRow.feeId}: ${parsed.errors.join('; ')}`);
    if (feeRow.entityTypeId && !entityTypeIds.has(feeRow.entityTypeId)) {
      throw new Error(`catalog fee ${feeRow.feeId} unknown entity type`);
    }
  }

  for (const entity of entityTypes) {
    if (!jurisdictionIds.has(entity.jurisdictionId)) {
      throw new Error(`entity type ${entity.entityTypeId} unknown jurisdiction`);
    }
  }

  return {
    schemaVersion: SCHEMA,
    researchDate: CATALOG_RESEARCH_DATE,
    freshnessPolicyVersion: FRESHNESS_POLICY.schemaVersion,
    jurisdictions: graph.value,
    authorities,
    sources,
    entityTypes,
    fees,
    rules,
  };
}
