/** ISO 3166-2 US states + DC. Structural inventory only — not reviewed legal facts. */
export const US_SUBNATIONAL = Object.freeze([
  { code: 'AL', name: 'Alabama', level: 'state' },
  { code: 'AK', name: 'Alaska', level: 'state' },
  { code: 'AZ', name: 'Arizona', level: 'state' },
  { code: 'AR', name: 'Arkansas', level: 'state' },
  { code: 'CA', name: 'California', level: 'state' },
  { code: 'CO', name: 'Colorado', level: 'state' },
  { code: 'CT', name: 'Connecticut', level: 'state' },
  { code: 'DE', name: 'Delaware', level: 'state' },
  { code: 'DC', name: 'District of Columbia', level: 'district' },
  { code: 'FL', name: 'Florida', level: 'state' },
  { code: 'GA', name: 'Georgia', level: 'state' },
  { code: 'HI', name: 'Hawaii', level: 'state' },
  { code: 'ID', name: 'Idaho', level: 'state' },
  { code: 'IL', name: 'Illinois', level: 'state' },
  { code: 'IN', name: 'Indiana', level: 'state' },
  { code: 'IA', name: 'Iowa', level: 'state' },
  { code: 'KS', name: 'Kansas', level: 'state' },
  { code: 'KY', name: 'Kentucky', level: 'state' },
  { code: 'LA', name: 'Louisiana', level: 'state' },
  { code: 'ME', name: 'Maine', level: 'state' },
  { code: 'MD', name: 'Maryland', level: 'state' },
  { code: 'MA', name: 'Massachusetts', level: 'state' },
  { code: 'MI', name: 'Michigan', level: 'state' },
  { code: 'MN', name: 'Minnesota', level: 'state' },
  { code: 'MS', name: 'Mississippi', level: 'state' },
  { code: 'MO', name: 'Missouri', level: 'state' },
  { code: 'MT', name: 'Montana', level: 'state' },
  { code: 'NE', name: 'Nebraska', level: 'state' },
  { code: 'NV', name: 'Nevada', level: 'state' },
  { code: 'NH', name: 'New Hampshire', level: 'state' },
  { code: 'NJ', name: 'New Jersey', level: 'state' },
  { code: 'NM', name: 'New Mexico', level: 'state' },
  { code: 'NY', name: 'New York', level: 'state' },
  { code: 'NC', name: 'North Carolina', level: 'state' },
  { code: 'ND', name: 'North Dakota', level: 'state' },
  { code: 'OH', name: 'Ohio', level: 'state' },
  { code: 'OK', name: 'Oklahoma', level: 'state' },
  { code: 'OR', name: 'Oregon', level: 'state' },
  { code: 'PA', name: 'Pennsylvania', level: 'state' },
  { code: 'RI', name: 'Rhode Island', level: 'state' },
  { code: 'SC', name: 'South Carolina', level: 'state' },
  { code: 'SD', name: 'South Dakota', level: 'state' },
  { code: 'TN', name: 'Tennessee', level: 'state' },
  { code: 'TX', name: 'Texas', level: 'state' },
  { code: 'UT', name: 'Utah', level: 'state' },
  { code: 'VT', name: 'Vermont', level: 'state' },
  { code: 'VA', name: 'Virginia', level: 'state' },
  { code: 'WA', name: 'Washington', level: 'state' },
  { code: 'WV', name: 'West Virginia', level: 'state' },
  { code: 'WI', name: 'Wisconsin', level: 'state' },
  { code: 'WY', name: 'Wyoming', level: 'state' },
]);
