import { Router } from 'express';
import { requireAuth, requireEmployerAuth } from '../middleware/auth.js';
import { secureTrustedOrigin } from '../middleware/secureTrustedOrigin.js';
import {
  authLimiter,
  employerAuthLimiter,
  forgotPasswordLimiter,
  refreshLimiter,
  verifyEmailLimiter,
  uploadLimiter,
} from '../middleware/rateLimit.js';
import { requireTurnstileWhenEnabled } from '../middleware/turnstile.js';
import { requireEmployerEmailVerified } from '../middleware/requireEmailVerified.js';
import { verifyRealmEmail } from '../controllers/realmVerifyEmailController.js';
import * as employerAuth from '../controllers/employerAuthController.js';
import * as employer from '../controllers/employerController.js';
import * as employerTeam from '../controllers/employerTeamController.js';
import * as employerUsage from '../controllers/employerUsageController.js';
import { createJobCheckout } from '../controllers/paymentsController.js';
import { extractEmployerJobFromDocument } from '../controllers/jobDocumentExtractController.js';
import { uploadJobDescription } from '../middleware/jobDescriptionUpload.js';
import { requireEmployerCapability } from '../services/employer/employerOrganizationService.js';
import { EMPLOYER_CAPABILITIES as C } from '../../../shared/employer/team.js';

export const employerRouter = Router();

employerRouter.post(
  '/auth/employer/register',
  employerAuthLimiter,
  secureTrustedOrigin,
  requireTurnstileWhenEnabled('register'),
  employerAuth.employerRegister
);
employerRouter.post(
  '/auth/employer/login',
  employerAuthLimiter,
  secureTrustedOrigin,
  employerAuth.employerLogin
);
employerRouter.post(
  '/auth/employer/refresh-token',
  refreshLimiter,
  secureTrustedOrigin,
  employerAuth.employerRefreshToken
);
employerRouter.post(
  '/auth/employer/logout',
  secureTrustedOrigin,
  requireAuth,
  requireEmployerAuth,
  employerAuth.employerLogout
);
employerRouter.post(
  '/auth/employer/logout-all',
  secureTrustedOrigin,
  requireAuth,
  requireEmployerAuth,
  employerAuth.employerLogoutAll
);
employerRouter.post(
  '/auth/employer/change-password',
  secureTrustedOrigin,
  requireAuth,
  requireEmployerAuth,
  employerAuth.employerChangePassword
);
employerRouter.post(
  '/auth/employer/forgot-password',
  secureTrustedOrigin,
  forgotPasswordLimiter,
  requireTurnstileWhenEnabled('password_recovery'),
  employerAuth.employerForgotPassword
);
employerRouter.post(
  '/auth/employer/verify-email',
  verifyEmailLimiter,
  verifyRealmEmail
);
employerRouter.post(
  '/auth/employer/reset-password',
  secureTrustedOrigin,
  authLimiter,
  employerAuth.employerResetPassword
);

employerRouter.get(
  '/employer/me',
  requireAuth,
  requireEmployerAuth,
  employerAuth.employerMe
);
employerRouter.get(
  '/employer/dashboard',
  requireAuth,
  requireEmployerAuth,
  employer.getDashboard
);
employerRouter.patch(
  '/employer/profile',
  requireAuth,
  requireEmployerAuth,
  employer.updateEmployerProfile
);
employerRouter.get(
  '/employer/plans',
  requireAuth,
  requireEmployerAuth,
  employer.getPlans
);
employerRouter.get(
  '/employer/plans/usage',
  requireAuth,
  requireEmployerAuth,
  requireEmployerCapability(C.USAGE_READ),
  employerUsage.getPlansUsage
);
employerRouter.get(
  '/employer/billing',
  requireAuth,
  requireEmployerAuth,
  requireEmployerCapability(C.BILLING_READ),
  employerUsage.getBillingOverview
);
employerRouter.get(
  '/employer/team',
  requireAuth,
  requireEmployerAuth,
  requireEmployerCapability(C.TEAM_READ),
  employerTeam.listTeam
);
employerRouter.get(
  '/employer/team/invites',
  requireAuth,
  requireEmployerAuth,
  requireEmployerCapability(C.TEAM_READ),
  employerTeam.listInvites
);
employerRouter.post(
  '/employer/team/invites',
  requireAuth,
  requireEmployerAuth,
  requireEmployerCapability(C.TEAM_MANAGE),
  employerTeam.createInvite
);
employerRouter.post(
  '/employer/team/invites/:invitationId/revoke',
  requireAuth,
  requireEmployerAuth,
  requireEmployerCapability(C.TEAM_MANAGE),
  employerTeam.revokeInvite
);
employerRouter.patch(
  '/employer/team/members/:membershipId',
  requireAuth,
  requireEmployerAuth,
  requireEmployerCapability(C.TEAM_MANAGE),
  employerTeam.updateMember
);
employerRouter.delete(
  '/employer/team/members/:membershipId',
  requireAuth,
  requireEmployerAuth,
  requireEmployerCapability(C.TEAM_MANAGE),
  employerTeam.deleteMember
);
employerRouter.get(
  '/auth/employer/invitations/preview',
  employerTeam.previewInvite
);
employerRouter.post(
  '/auth/employer/invitations/accept',
  requireAuth,
  requireEmployerAuth,
  employerTeam.acceptInvite
);
employerRouter.get(
  '/employer/interviews',
  requireAuth,
  requireEmployerAuth,
  requireEmployerCapability(C.INTERVIEWS_READ),
  employer.getInterviews
);
employerRouter.get(
  '/employer/jobs',
  requireAuth,
  requireEmployerAuth,
  employer.getMyJobs
);
// Registered before '/employer/jobs/:id' so the literal path is not captured as
// an :id param.
employerRouter.get(
  '/employer/jobs/selector',
  requireAuth,
  requireEmployerAuth,
  employer.getJobSelectorOptions
);
employerRouter.post(
  '/employer/jobs/extract-from-document',
  requireAuth,
  requireEmployerAuth,
  requireEmployerCapability(C.JOBS_WRITE),
  uploadLimiter,
  (req, res, next) => {
    uploadJobDescription(req, res, (err) => {
      if (err) return res.status(400).json({ error: err.message || 'File upload failed', code: 'invalid_file_content' });
      next();
    });
  },
  extractEmployerJobFromDocument
);
employerRouter.get(
  '/employer/jobs/:id',
  requireAuth,
  requireEmployerAuth,
  employer.getJob
);
employerRouter.post(
  '/employer/jobs',
  requireAuth,
  requireEmployerAuth,
  requireEmployerCapability(C.JOBS_WRITE),
  employer.createJob
);
employerRouter.patch(
  '/employer/jobs/:id',
  requireAuth,
  requireEmployerAuth,
  requireEmployerCapability(C.JOBS_WRITE),
  employer.updateJob
);
employerRouter.post(
  '/employer/jobs/:id/close',
  requireAuth,
  requireEmployerAuth,
  requireEmployerCapability(C.JOBS_WRITE),
  employer.closeJob
);
employerRouter.post(
  '/employer/jobs/:id/reopen',
  requireAuth,
  requireEmployerAuth,
  requireEmployerCapability(C.JOBS_WRITE),
  employer.reopenJob
);
employerRouter.post(
  '/employer/jobs/:id/activate',
  requireAuth,
  requireEmployerAuth,
  requireEmployerEmailVerified(),
  requireEmployerCapability(C.JOBS_WRITE),
  employer.activateJob
);
employerRouter.post(
  '/employer/jobs/:id/checkout',
  requireAuth,
  requireEmployerAuth,
  requireEmployerEmailVerified(),
  createJobCheckout
);
employerRouter.get(
  '/employer/jobs/:id/applications',
  requireAuth,
  requireEmployerAuth,
  employer.getJobApplications
);
employerRouter.get(
  '/employer/analytics/:jobId',
  requireAuth,
  requireEmployerAuth,
  employer.getJobAnalytics
);
employerRouter.get(
  '/employer/applications/:id',
  requireAuth,
  requireEmployerAuth,
  employer.getApplicationDetail
);
employerRouter.get(
  '/employer/applications/:id/resume',
  requireAuth,
  requireEmployerAuth,
  employer.getApplicationResume
);
employerRouter.patch(
  '/employer/applications/:id',
  requireAuth,
  requireEmployerAuth,
  requireEmployerCapability(C.APPLICATIONS_WRITE),
  employer.updateApplicationStatus
);
