import { Router } from 'express';
import { requireAuth, requireEmployerAuth } from '../middleware/auth.js';
import { secureTrustedOrigin } from '../middleware/secureTrustedOrigin.js';
import {
  authLimiter,
  employerAuthLimiter,
  forgotPasswordLimiter,
  refreshLimiter,
} from '../middleware/rateLimit.js';
import * as employerAuth from '../controllers/employerAuthController.js';
import * as employer from '../controllers/employerController.js';
import { createJobCheckout } from '../controllers/paymentsController.js';

export const employerRouter = Router();

employerRouter.post(
  '/auth/employer/register',
  employerAuthLimiter,
  secureTrustedOrigin,
  employerAuth.employerRegister
);
employerRouter.post(
  '/auth/employer/login',
  employerAuthLimiter,
  secureTrustedOrigin,
  employerAuth.employerLogin
);
employerRouter.post(
  '/auth/employer/refresh-token',
  refreshLimiter,
  secureTrustedOrigin,
  employerAuth.employerRefreshToken
);
employerRouter.post(
  '/auth/employer/logout',
  secureTrustedOrigin,
  requireAuth,
  requireEmployerAuth,
  employerAuth.employerLogout
);
employerRouter.post(
  '/auth/employer/logout-all',
  secureTrustedOrigin,
  requireAuth,
  requireEmployerAuth,
  employerAuth.employerLogoutAll
);
employerRouter.post(
  '/auth/employer/change-password',
  secureTrustedOrigin,
  requireAuth,
  requireEmployerAuth,
  employerAuth.employerChangePassword
);
employerRouter.post(
  '/auth/employer/forgot-password',
  secureTrustedOrigin,
  forgotPasswordLimiter,
  employerAuth.employerForgotPassword
);
employerRouter.post(
  '/auth/employer/reset-password',
  secureTrustedOrigin,
  authLimiter,
  employerAuth.employerResetPassword
);

employerRouter.get(
  '/employer/me',
  requireAuth,
  requireEmployerAuth,
  employerAuth.employerMe
);
employerRouter.get(
  '/employer/dashboard',
  requireAuth,
  requireEmployerAuth,
  employer.getDashboard
);
employerRouter.patch(
  '/employer/profile',
  requireAuth,
  requireEmployerAuth,
  employer.updateEmployerProfile
);
employerRouter.get(
  '/employer/plans',
  requireAuth,
  requireEmployerAuth,
  employer.getPlans
);
employerRouter.get(
  '/employer/jobs',
  requireAuth,
  requireEmployerAuth,
  employer.getMyJobs
);
// Registered before '/employer/jobs/:id' so the literal path is not captured as
// an :id param.
employerRouter.get(
  '/employer/jobs/selector',
  requireAuth,
  requireEmployerAuth,
  employer.getJobSelectorOptions
);
employerRouter.get(
  '/employer/jobs/:id',
  requireAuth,
  requireEmployerAuth,
  employer.getJob
);
employerRouter.post(
  '/employer/jobs',
  requireAuth,
  requireEmployerAuth,
  employer.createJob
);
employerRouter.patch(
  '/employer/jobs/:id',
  requireAuth,
  requireEmployerAuth,
  employer.updateJob
);
employerRouter.post(
  '/employer/jobs/:id/close',
  requireAuth,
  requireEmployerAuth,
  employer.closeJob
);
employerRouter.post(
  '/employer/jobs/:id/reopen',
  requireAuth,
  requireEmployerAuth,
  employer.reopenJob
);
employerRouter.post(
  '/employer/jobs/:id/activate',
  requireAuth,
  requireEmployerAuth,
  employer.activateJob
);
employerRouter.post(
  '/employer/jobs/:id/checkout',
  requireAuth,
  requireEmployerAuth,
  createJobCheckout
);
employerRouter.get(
  '/employer/jobs/:id/applications',
  requireAuth,
  requireEmployerAuth,
  employer.getJobApplications
);
employerRouter.get(
  '/employer/analytics/:jobId',
  requireAuth,
  requireEmployerAuth,
  employer.getJobAnalytics
);
employerRouter.patch(
  '/employer/applications/:id',
  requireAuth,
  requireEmployerAuth,
  employer.updateApplicationStatus
);
