import { asyncHandler } from '../utils/asyncHandler.js'; import { parseMoney } from '../../../shared/international/money.js'; import { CommerceAccount } from '../models/commerce/CommerceAccount.js'; import { CommerceLedgerEntry } from '../models/commerce/CommerceLedgerEntry.js'; import { CommerceProduct } from '../models/commerce/CommerceProduct.js'; import { CommerceOrder } from '../models/commerce/CommerceOrder.js'; import { CommerceTransaction } from '../models/commerce/CommerceTransaction.js'; import { CommerceRefund } from '../models/commerce/CommerceRefund.js'; import { CommercePayoutReadiness, CommerceReconciliation } from '../models/commerce/CommerceOperations.js'; import { AgentMembership } from '../models/agent/AgentMembership.js'; import { logAudit, auditFromRequest } from '../services/auditService.js'; import * as commerce from '../services/commerceService.js';
const page=(q)=>({limit:Math.min(100,Math.max(1,Number.parseInt(q.limit,10)||20)),page:Math.max(1,Number.parseInt(q.page,10)||1)});const audit=(req,action,targetType,targetId,metadata={})=>logAudit(auditFromRequest(req,{actor:req.user||req.employer||req.agent,action,targetType,targetId,metadata}));
async function principalScope(req){if(req.user)return{ownerType:'user',ownerId:req.user.userId};if(req.employer)return{ownerType:'employer',ownerId:req.employer.employerId};if(req.agent){const m=await AgentMembership.findOne({agentAccountId:req.agent.agentAccountId,active:true});if(!m)throw Object.assign(new Error('Active organization membership required'),{status:403});return{ownerType:'organization',ownerId:m.organizationId};}throw Object.assign(new Error('Authentication required'),{status:401});}
export const listProducts=asyncHandler(async(req,res)=>{const filter={active:true,publicVisible:true,...(req.query.audience?{audience:req.query.audience}:{})};res.json({products:await CommerceProduct.find(filter).sort({slug:1,version:-1}).limit(100)});});
export const createOrder=asyncHandler(async(req,res)=>{const scope=await principalScope(req);const order=await commerce.createOrder({...scope,productId:req.body?.productId,quantity:req.body?.quantity,idempotencyKey:req.headers['idempotency-key']||req.body?.idempotencyKey});await audit(req,'commerce.order.created','CommerceOrder',order._id,{amountMinor:order.amountMinor,currency:order.currency,status:order.status});res.status(201).json({order,paymentMessage:'Payments are not configured. This order has not been paid.'});});
export const history=asyncHandler(async(req,res)=>{const scope=await principalScope(req),p=page(req.query),query={purchaserType:scope.ownerType,purchaserId:scope.ownerId};const [orders,transactions]=await Promise.all([CommerceOrder.find(query).sort({createdAt:-1}).skip((p.page-1)*p.limit).limit(p.limit),CommerceTransaction.find({'payer.ownerType':scope.ownerType,'payer.ownerId':scope.ownerId}).sort({createdAt:-1}).skip((p.page-1)*p.limit).limit(p.limit)]);res.json({orders,transactions,pagination:p});});
export const balances=asyncHandler(async(req,res)=>{const scope=await principalScope(req);const accounts=await CommerceAccount.find(scope);const derived=[];for(const account of accounts){if(account.accountType==='credits'&&req.query.creditType)derived.push({accountId:account._id,...await commerce.deriveBalance(account._id,{entryType:'credit_unit',creditType:req.query.creditType})});else if(account.accountType==='commerce'&&req.query.currency)derived.push({accountId:account._id,...await commerce.deriveBalance(account._id,{entryType:'fiat',currency:req.query.currency})});}res.json({balances:derived,source:'immutable_ledger'});});
export const requestRefund=asyncHandler(async(req,res)=>{const scope=await principalScope(req);const refund=await commerce.requestRefund({...scope,requesterType:scope.ownerType,requesterId:scope.ownerId,transactionId:req.body?.transactionId,amountMinor:req.body?.amountMinor,currency:req.body?.currency,reason:req.body?.reason,idempotencyKey:req.headers['idempotency-key']||req.body?.idempotencyKey});await audit(req,'commerce.refund.requested','CommerceRefund',refund._id,{amountMinor:refund.amountMinor,currency:refund.currency,status:'requested'});res.status(201).json({refund,message:'Refund requested. No provider refund has been executed.'});});
export const adminCreateProduct=asyncHandler(async(req,res)=>{const price=parseMoney(req.body?.price);if(!price||price.amountMinor<0)return res.status(400).json({error:'Valid non-negative Money price is required'});const product=await CommerceProduct.create({...req.body,price,active:req.body.active===true,version:Number(req.body.version)});await audit(req,'commerce.product.changed','CommerceProduct',product._id,{slug:product.slug,version:product.version,amountMinor:price.amountMinor,currency:price.currency});res.status(201).json({product});});
export const adminList=asyncHandler(async(req,res)=>{const p=page(req.query);const models={products:CommerceProduct,orders:CommerceOrder,transactions:CommerceTransaction,ledger:CommerceLedgerEntry,refunds:CommerceRefund,reconciliation:CommerceReconciliation,payouts:CommercePayoutReadiness};const Model=models[req.params.kind];if(!Model)return res.status(400).json({error:'Unsupported commerce view'});const query={...(req.query.status?{status:req.query.status}:{}),...(req.query.currency?{currency:req.query.currency}:{})};const items=await Model.find(query).sort({createdAt:-1}).skip((p.page-1)*p.limit).limit(p.limit);res.json({items,pagination:p,immutable:req.params.kind==='ledger'});});
export const adminIssueCredits=asyncHandler(async(req,res)=>{const lot=await commerce.issueCredits({...req.body,idempotencyKey:req.headers['idempotency-key']||req.body?.idempotencyKey,source:'admin'});await audit(req,'commerce.credit.issued','CommerceCreditLot',lot._id,{creditType:lot.creditType,quantity:lot.quantityIssued});res.status(201).json({creditLot:lot});});
export const adminReverse=asyncHandler(async(req,res)=>{const entry=await commerce.reverseLedgerEntry({entryId:req.params.entryId,idempotencyKey:req.headers['idempotency-key']||req.body?.idempotencyKey,reason:req.body?.reason,actorRole:req.user.role});await audit(req,'commerce.ledger.reversal','CommerceLedgerEntry',entry._id,{reversesEntryId:entry.reversesEntryId});res.status(201).json({entry});});
