import {asyncHandler} from '../utils/asyncHandler.js';import {stripeConnectProvider} from '../services/payments/StripeConnectProvider.js';import * as payments from '../services/marketplacePaymentService.js';import {clientPaymentAuthorityFields} from '../../../shared/commerce/contracts.js';import {isLocalMarketplaceSimulationAllowed,simulateConnectReady,simulateStudentPaymentEvent,simulateRefundEvent} from '../services/marketplaceSimulationService.js';import {logAudit,auditFromRequest} from '../services/auditService.js';
const SITE=(process.env.SITE_URL||process.env.FRONTEND_URL||'http://localhost:5173').replace(/\/$/,'');const audit=(req,action,targetType,targetId,metadata={})=>logAudit(auditFromRequest(req,{actor:req.user||req.agent,action,targetType,targetId,metadata}));
function rejectAuthority(req,res){const fields=clientPaymentAuthorityFields(req.body);if(!fields.length)return false;res.status(400).json({error:'Client cannot set payment authority fields',code:'mass_assignment_rejected'});return true;}
export const configuration=(req,res)=>res.json({provider:'stripe',state:stripeConnectProvider.configurationState(),chargeStrategy:'destination_charge',publishableKey:process.env.STRIPE_PUBLISHABLE_KEY||null,simulation:isLocalMarketplaceSimulationAllowed(req)?{available:true,liveProvider:false}:{available:false}});
export const startOnboarding=asyncHandler(async(req,res)=>{const result=await payments.startConnectOnboarding(req.agent.agentAccountId,{country:req.body?.country,refreshUrl:`${SITE}/agent/commerce?connect=refresh`,returnUrl:`${SITE}/agent/commerce?connect=return`,idempotencyKey:req.headers['idempotency-key']||req.body?.idempotencyKey});await audit(req,'marketplace.connect.onboarding_initiated','Organization','self',{provider:'stripe'});res.status(201).json(result);});
export const syncOnboarding=asyncHandler(async(req,res)=>{const status=await payments.syncConnectStatus(req.agent.agentAccountId);await audit(req,'marketplace.connect.status_synchronized','Organization','self',{provider:'stripe',ready:status.ready,providerKycStatus:status.providerKycStatus});res.json({status});});
export const createIntent=asyncHandler(async(req,res)=>{if(rejectAuthority(req,res))return;const result=await payments.createMarketplacePaymentIntent(req.user.userId,{orderId:req.body?.orderId,idempotencyKey:req.headers['idempotency-key']||req.body?.idempotencyKey});await audit(req,'marketplace.payment_intent.initiated','CommerceOrder',req.body?.orderId,{provider:'stripe',state:result.state,chargeStrategy:'destination_charge'});res.status(201).json(result);});
export const createServiceOrder=asyncHandler(async(req,res)=>{if(rejectAuthority(req,res))return;const order=await payments.createPaidServiceOrder(req.user.userId,{serviceId:req.body?.serviceId,consultationId:req.body?.consultationId,idempotencyKey:req.headers['idempotency-key']||req.body?.idempotencyKey});await audit(req,'marketplace.order.created','CommerceOrder',order._id,{amountMinor:order.amountMinor,currency:order.currency,sellerOrganizationId:order.sellerOrganizationId});res.status(201).json({order,message:'Order created. It is not paid until a verified provider event confirms payment.',paid:false});});
export const simulateConnect=asyncHandler(async(req,res)=>{const status=await simulateConnectReady(req.agent.agentAccountId,req);await audit(req,'marketplace.simulation.connect','Organization','self',{provider:'simulation',ready:status.ready});res.status(201).json({status,liveProviderCalled:false});});
export const simulatePayment=asyncHandler(async(req,res)=>{const result=await simulateStudentPaymentEvent(req.user.userId,{orderId:req.body?.orderId,outcome:req.body?.outcome||'succeeded'},req);await audit(req,'marketplace.simulation.payment','CommerceOrder',req.body?.orderId,{outcome:req.body?.outcome||'succeeded',liveProviderCalled:false});res.json({result,liveProviderCalled:false});});
export const simulateRefund=asyncHandler(async(req,res)=>{const result=await simulateRefundEvent(req.user.userId,{refundId:req.body?.refundId},req);await audit(req,'marketplace.simulation.refund','CommerceRefund',req.body?.refundId,{liveProviderCalled:false});res.json({result,liveProviderCalled:false});});
export const initiateRefund=asyncHandler(async(req,res)=>{const result=await payments.initiateProviderRefund(req.params.refundId,req.user.userId);await audit(req,'marketplace.refund.initiated','CommerceRefund',req.params.refundId,{provider:'stripe',status:result.status,reverseTransfer:true,refundApplicationFee:true});res.status(202).json(result);});
export const marketplaceWebhook=asyncHandler(async(req,res)=>{const signature=req.headers['stripe-signature'];let event;try{event=stripeConnectProvider.constructWebhookEvent(req.body,signature);}catch(error){return res.status(error.status||400).json({error:'Invalid marketplace webhook',code:error.code||'invalid_signature'});}if(event.account&&event.data?.object)event.data.object.account=event.account;const result=await payments.processMarketplaceWebhook(event);res.json({received:true,...result});});
