import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs'; import { ProfessionalReview } from '../models/trust/ProfessionalReview.js'; import { ProfessionalReport } from '../models/trust/ProfessionalReport.js'; import { ProfessionalDispute } from '../models/trust/ProfessionalDispute.js'; import { publicReviewProjection } from '../services/professionalTrustService.js';
const read=(p)=>fs.readFileSync(new URL(p,import.meta.url),'utf8'); const service=read('../services/professionalTrustService.js'),routes=read('../routes/professionalTrust.js'),controller=read('../controllers/professionalTrustController.js'),reviewModel=read('../models/trust/ProfessionalReview.js'),reportModel=read('../models/trust/ProfessionalReport.js'),notificationModel=read('../models/trust/TrustNotificationEvent.js'),vault=read('../services/vault/vaultAccessPolicy.js'),constants=read('../../../shared/services/professionalTrust.js');
const check=(name,fn)=>test(name,fn);
check('1 completed eligible interaction allows review',()=>assert.match(service,/status === 'completed'/));
check('2 ineligible interaction denied',()=>assert.match(service,/Interaction is not review eligible/));
check('3 arbitrary Agent review denied',()=>assert.deepEqual(ProfessionalReview.schema.path('interactionType').enumValues,['consultation','professional_case']));
check('4 review owner derived server-side',()=>assert.match(controller,/req\.user\.userId,req\.body/));
check('5 duplicate interaction review denied',()=>assert.match(reviewModel,/unique: true/));
check('6 cross-user review denied',()=>assert.match(service,/studentUserId, interactionType, interactionId/));
check('7 verifiedInteraction cannot be client-forged',()=>assert.match(service,/verifiedInteraction: true/));
check('8 rating bounds',()=>{const x=new ProfessionalReview({rating:6});assert.ok(x.validateSync()?.errors.rating);});
check('9 bounded safe review text',()=>{assert.equal(ProfessionalReview.schema.path('body').options.maxlength,4000);assert.match(service,/sanitizeHtml/);});
check('10 Agent cannot edit Student review',()=>assert.doesNotMatch(routes,/agent\/reviews\/:reviewId[^\n]*patch/i));
check('11 Agent response ownership',()=>assert.match(service,/organizationId: membership\.organizationId/));
check('12 cross-agency response denied',()=>assert.match(service,/Review not found in Agent organization/));
check('13 public safe review projection',()=>{const p=publicReviewProjection({_id:'1',rating:5,body:'good',interactionType:'consultation',publishedAt:new Date()});assert.equal(p.verifiedInteraction,true);});
check('14 private Student data hidden',()=>assert.doesNotMatch(JSON.stringify(publicReviewProjection({_id:'1',rating:5,body:'good'})),/email/));
check('15 aggregate uses eligible public reviews only',()=>assert.match(service,/status: 'published', verifiedInteraction: true/));
check('16 empty aggregate truthful',()=>assert.match(service,/averageRating: null, reviewCount: 0/));
check('17 report target validation',()=>assert.ok(ProfessionalReport.schema.path('targetType').enumValues.length>=6));
check('18 reporter ownership and identity',()=>assert.equal(ProfessionalReport.schema.path('reporterUserId').options.required,true));
check('19 Agent cannot browse arbitrary reporters',()=>assert.doesNotMatch(controller,/agentReports[\s\S]{0,500}reporterUserId/));
check('20 report lifecycle transitions',()=>assert.ok(ProfessionalReport.schema.path('status').enumValues.includes('triaged')));
check('21 report is not automatic guilt',()=>assert.equal(new ProfessionalReport({}).status,'submitted'));
check('22 dispute requires legitimate interaction',()=>assert.match(service,/resolveInteraction\(studentUserId/));
check('23 dispute participant authorization',()=>assert.match(service,/const scope = actorType === 'student'/));
check('24 cross-dispute IDOR denied',()=>assert.match(service,/findOne\(\{ _id: disputeId, \.\.\.scope \}\)/));
check('25 dispute history append',()=>assert.match(service,/events\.push/));
check('26 party cannot declare Admin resolution',()=>assert.match(service,/\['resolved', 'closed', 'dismissed', 'escalated'/));
check('27 payment actions unavailable',()=>assert.doesNotMatch(routes,/refund|chargeback|payout|escrow/i));
check('28 dispute gives zero Vault access',()=>assert.doesNotMatch(service,/DocumentAccessGrant|VaultDocument/));
check('29 message contents not leaked',()=>assert.doesNotMatch(reportModel,/message.*(?:body|text)/i));
check('30 moderation review boundary authorized',()=>assert.match(routes,/requirePermission\(PERMISSIONS\.MODERATE_REPORTS\),c\.moderationQueue/));
check('31 Moderator and Admin separation',()=>assert.match(service,/Admin authority required for resolution/));
check('32 serious action reuses verification authority',()=>assert.match(constants,/organization_suspension_recommended/));
check('33 content moderation action',()=>assert.match(constants,/content_hidden/));
check('34 audit metadata safe',()=>assert.doesNotMatch(controller,/messageBody|documentContent|storageKey|email/));
check('35 notifications pending, never delivered',()=>{assert.match(notificationModel,/enum: \['pending'\]/);assert.match(notificationModel,/deliveryAttempted/);});
check('36 User cannot mutate Agent endpoints',()=>assert.match(routes,/const s=\[\.\.\.studentProductAuth\],a=\[requireAuth,requireAgentAuth\]/));
check('37 Employer cannot mutate Agent endpoints',()=>assert.match(routes,/requireAgentAuth/));
check('38 public profile review integration',()=>assert.match(routes,/agents\/:slug\/reviews/));
check('39 Agent cannot delete negative review',()=>assert.doesNotMatch(routes,/delete\('\/agent\/reviews/i));
check('40 truthful verified semantics',()=>assert.match(service,/Strideto does not verify or endorse every statement|VERIFIED_REVIEW_COPY/));
check('models enforce explicit lifecycles',()=>{assert.ok(ProfessionalDispute.schema.path('status').enumValues.includes('escalated'));assert.ok(ProfessionalReview.schema.path('status').enumValues.includes('removed'));});
check('Vault policy remains independently authoritative',()=>assert.match(vault,/canAccessDocument/));
