import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { agentApi } from '../../services/agentService';
import { ROUTES } from '../../constants';

export default function AgentMarketplace() {
  const { t } = useTranslation('common'); const [data,setData]=useState({posts:[],total:0}); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [busy,setBusy]=useState('');
  const load=()=>agentApi.getMarketplacePosts().then(r=>setData(r.data));
  useEffect(()=>{load().catch(e=>setError(e.response?.data?.error||t('error',{defaultValue:'Unable to load marketplace posts.'}))).finally(()=>setLoading(false));},[]);
  const action=async(post,kind)=>{setBusy(post._id);setError('');try{if(kind==='submit')await agentApi.submitMarketplacePost(post._id);else await agentApi.archiveMarketplacePost(post._id);await load();}catch(e){setError(e.response?.data?.error||'Action failed.');}finally{setBusy('');}};
  if(loading)return <p className="text-sm text-slate-500">{t('loading',{defaultValue:'Loading…'})}</p>;
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">Agent marketplace</h1><p className="mt-1 text-sm text-slate-500">Structured professional posts with independent moderation.</p></div><Link to={ROUTES.AGENT_MARKETPLACE_NEW} className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-medium text-white">Create draft</Link></div>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{data.posts.length===0?<p className="rounded-xl border bg-white p-6 text-sm text-slate-500">No marketplace posts yet.</p>:<div className="space-y-3">{data.posts.map(post=><article key={post._id} className="rounded-xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs uppercase text-slate-500">{post.postType.replaceAll('_',' ')}</p><h2 className="font-semibold">{post.title}</h2><p className="mt-1 text-sm text-slate-600">{post.summary}</p></div><div className="text-right text-xs"><p>Publication: {post.publicationStatus}</p><p>Moderation: {post.moderationStatus}</p></div></div>{post.moderationFeedback&&<p className="mt-3 rounded bg-amber-50 p-2 text-sm text-amber-800">Moderator feedback: {post.moderationFeedback}</p>}<div className="mt-4 flex gap-4 text-sm"><Link className="text-blue-700" to={`${ROUTES.AGENT_MARKETPLACE}/${post._id}/edit`}>Edit</Link>{(post.moderationStatus==='not_submitted'||post.moderationStatus==='needs_changes')&&<button disabled={busy===post._id} onClick={()=>action(post,'submit')} className="text-green-700 disabled:opacity-50">Submit for review</button>}{post.publicationStatus!=='archived'&&<button disabled={busy===post._id} onClick={()=>action(post,'archive')} className="text-slate-600 disabled:opacity-50">Archive</button>}</div></article>)}</div>}</div>;
}
