/**
 * Narrow Business Services provider capability taxonomy (Phase 17D-2).
 *
 * Additive to 17D-1 ProviderCapability. No fifth auth realm.
 * Public role: Business Services Provider. Formation specialization:
 * Business Formation Provider. These are capability labels, not User.role.
 */
import { PROVIDER_SUBJECT_TYPES } from './constants.js';

export const GBS_CAPABILITY_SCHEMA_VERSION = '17d-2.0';

export const BUSINESS_SERVICES_CAPABILITY_IDS = Object.freeze({
  BUSINESS_FORMATION: 'business_formation',
  FORMATION_CONSULTATION: 'formation_consultation',
  DOCUMENT_PREPARATION: 'document_preparation',
  REGISTERED_AGENT: 'registered_agent',
  REGISTERED_OFFICE: 'registered_office',
  EIN_ASSISTANCE: 'ein_assistance',
  NAME_AVAILABILITY: 'name_availability',
  BENEFICIAL_OWNER_FILING: 'beneficial_owner_filing',
  OPERATING_AGREEMENT: 'operating_agreement',
  ANNUAL_REPORT_RENEWAL: 'annual_report_renewal',
  BUSINESS_LICENSE: 'business_license',
  FOREIGN_QUALIFICATION: 'foreign_qualification',
  COMPANY_AMENDMENT: 'company_amendment',
  COMPANY_DISSOLUTION: 'company_dissolution',
  GOOD_STANDING: 'good_standing',
  TAX_REGISTRATION: 'tax_registration',
  VAT_GST_REGISTRATION: 'vat_gst_registration',
  PAYROLL_REGISTRATION: 'payroll_registration',
  BOOKKEEPING: 'bookkeeping',
  BANK_ACCOUNT_ASSISTANCE: 'bank_account_assistance',
  PAYMENT_PLATFORM_ASSISTANCE: 'payment_platform_assistance',
  MERCHANT_ACCOUNT_ASSISTANCE: 'merchant_account_assistance',
  BUSINESS_ADDRESS: 'business_address',
  NOTARIZATION: 'notarization',
  APOSTILLE: 'apostille',
  COMPLIANCE_CONSULTATION: 'compliance_consultation',
});

export const BUSINESS_SERVICES_PROVIDER_ROLE_LABEL = 'Business Services Provider';
export const BUSINESS_FORMATION_PROVIDER_LABEL = 'Business Formation Provider';

const BOTH = Object.freeze([PROVIDER_SUBJECT_TYPES.AGENT, PROVIDER_SUBJECT_TYPES.ORGANIZATION]);

export const BUSINESS_SERVICES_CAPABILITIES = Object.freeze({
  [BUSINESS_SERVICES_CAPABILITY_IDS.BUSINESS_FORMATION]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.BUSINESS_FORMATION,
    publicName: 'Business formation',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: true,
    evidenceRequired: true,
    organizationVerificationRequired: false,
    reviewRequired: true,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.FORMATION_CONSULTATION]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.FORMATION_CONSULTATION,
    publicName: 'Formation consultation',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: true,
    organizationVerificationRequired: false,
    reviewRequired: true,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.DOCUMENT_PREPARATION]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.DOCUMENT_PREPARATION,
    publicName: 'Document preparation',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: true,
    evidenceRequired: true,
    organizationVerificationRequired: false,
    reviewRequired: true,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.REGISTERED_AGENT]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.REGISTERED_AGENT,
    publicName: 'Registered agent',
    regulated: true,
    protectedTitleRequired: true,
    requiredProtectedTitleId: 'registered_agent',
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: true,
    organizationVerificationRequired: false,
    reviewRequired: true,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.REGISTERED_OFFICE]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.REGISTERED_OFFICE,
    publicName: 'Registered office',
    regulated: true,
    protectedTitleRequired: true,
    requiredProtectedTitleId: 'registered_office_provider',
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: true,
    organizationVerificationRequired: false,
    reviewRequired: true,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.EIN_ASSISTANCE]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.EIN_ASSISTANCE,
    publicName: 'EIN assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: true,
    organizationVerificationRequired: false,
    reviewRequired: true,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.NAME_AVAILABILITY]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.NAME_AVAILABILITY,
    publicName: 'Name availability / reservation assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: false,
    organizationVerificationRequired: false,
    reviewRequired: false,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.BENEFICIAL_OWNER_FILING]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.BENEFICIAL_OWNER_FILING,
    publicName: 'Beneficial-owner / ownership filing assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: true,
    organizationVerificationRequired: false,
    reviewRequired: true,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.OPERATING_AGREEMENT]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.OPERATING_AGREEMENT,
    publicName: 'Operating agreement / bylaws assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: true,
    evidenceRequired: false,
    organizationVerificationRequired: false,
    reviewRequired: false,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.ANNUAL_REPORT_RENEWAL]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.ANNUAL_REPORT_RENEWAL,
    publicName: 'Annual report / state renewal filing assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: true,
    organizationVerificationRequired: false,
    reviewRequired: true,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.BUSINESS_LICENSE]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.BUSINESS_LICENSE,
    publicName: 'Business license / permit assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: true,
    organizationVerificationRequired: false,
    reviewRequired: true,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.FOREIGN_QUALIFICATION]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.FOREIGN_QUALIFICATION,
    publicName: 'Foreign qualification / foreign registration assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: true,
    organizationVerificationRequired: false,
    reviewRequired: true,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.COMPANY_AMENDMENT]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.COMPANY_AMENDMENT,
    publicName: 'Company amendment filing assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: true,
    organizationVerificationRequired: false,
    reviewRequired: true,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.COMPANY_DISSOLUTION]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.COMPANY_DISSOLUTION,
    publicName: 'Company dissolution / closure assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: true,
    organizationVerificationRequired: false,
    reviewRequired: true,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.GOOD_STANDING]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.GOOD_STANDING,
    publicName: 'Certificate / good-standing document assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: false,
    organizationVerificationRequired: false,
    reviewRequired: false,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.TAX_REGISTRATION]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.TAX_REGISTRATION,
    publicName: 'Tax-registration assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: true,
    organizationVerificationRequired: false,
    reviewRequired: true,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.VAT_GST_REGISTRATION]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.VAT_GST_REGISTRATION,
    publicName: 'VAT / GST registration assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: true,
    organizationVerificationRequired: false,
    reviewRequired: true,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.PAYROLL_REGISTRATION]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.PAYROLL_REGISTRATION,
    publicName: 'Payroll-registration assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: true,
    organizationVerificationRequired: false,
    reviewRequired: true,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.BOOKKEEPING]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.BOOKKEEPING,
    publicName: 'Bookkeeping / accounting assistance or referral',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: false,
    entityTypeScoped: false,
    evidenceRequired: false,
    organizationVerificationRequired: false,
    reviewRequired: false,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.BANK_ACCOUNT_ASSISTANCE]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.BANK_ACCOUNT_ASSISTANCE,
    publicName: 'Bank-account application assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: false,
    entityTypeScoped: false,
    evidenceRequired: false,
    organizationVerificationRequired: false,
    reviewRequired: false,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.PAYMENT_PLATFORM_ASSISTANCE]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.PAYMENT_PLATFORM_ASSISTANCE,
    publicName: 'Payment-platform onboarding assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: false,
    entityTypeScoped: false,
    evidenceRequired: false,
    organizationVerificationRequired: false,
    reviewRequired: false,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.MERCHANT_ACCOUNT_ASSISTANCE]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.MERCHANT_ACCOUNT_ASSISTANCE,
    publicName: 'Merchant-account onboarding assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: false,
    entityTypeScoped: false,
    evidenceRequired: false,
    organizationVerificationRequired: false,
    reviewRequired: false,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.BUSINESS_ADDRESS]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.BUSINESS_ADDRESS,
    publicName: 'Business address / mail-handling services',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: false,
    organizationVerificationRequired: false,
    reviewRequired: false,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.NOTARIZATION]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.NOTARIZATION,
    publicName: 'Document notarization / legalization assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: false,
    organizationVerificationRequired: false,
    reviewRequired: false,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.APOSTILLE]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.APOSTILLE,
    publicName: 'Apostille assistance',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: false,
    organizationVerificationRequired: false,
    reviewRequired: false,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
  [BUSINESS_SERVICES_CAPABILITY_IDS.COMPLIANCE_CONSULTATION]: Object.freeze({
    capabilityId: BUSINESS_SERVICES_CAPABILITY_IDS.COMPLIANCE_CONSULTATION,
    publicName: 'Compliance consultation',
    regulated: false,
    protectedTitleRequired: false,
    jurisdictionScoped: true,
    entityTypeScoped: false,
    evidenceRequired: true,
    organizationVerificationRequired: false,
    reviewRequired: true,
    allowedSubjectTypes: BOTH,
    schemaVersion: GBS_CAPABILITY_SCHEMA_VERSION,
  }),
});

export function isKnownBusinessServicesCapability(id) {
  return Object.prototype.hasOwnProperty.call(BUSINESS_SERVICES_CAPABILITIES, id);
}

export function getBusinessServicesCapability(id) {
  return BUSINESS_SERVICES_CAPABILITIES[id] || null;
}

export function capabilityAllowsSubject(capabilityId, subjectType) {
  const def = getBusinessServicesCapability(capabilityId);
  return !!def && def.allowedSubjectTypes.includes(subjectType);
}
