import test from 'node:test';
import assert from 'node:assert/strict';
import { discoverEmployerBoards, normalizeDiscoveryRecord, normalizeHistory, validateBoardConfig } from './employer-board-discovery.mjs';

const greenhouseBoard = { company: 'Green Co', sourceType: 'GREENHOUSE', boardUrl: 'https://boards-api.greenhouse.io/v1/boards/green/jobs' };
const leverBoard = { company: 'Lever Co', sourceType: 'LEVER', boardUrl: 'https://api.lever.co/v0/postings/lever?mode=json' };
const jobs = {
  [greenhouseBoard.boardUrl]: { jobs: [{ id: 1, title: 'Engineer', absolute_url: 'https://boards.greenhouse.io/green/jobs/1', location: { name: 'Remote' }, company: { name: 'Green Co' } }] },
  [leverBoard.boardUrl]: [{ id: 'l-1', text: 'Designer', hostedUrl: 'https://jobs.lever.co/lever/l-1', applyUrl: 'https://jobs.lever.co/lever/l-1/apply', categories: { location: 'London', commitment: 'Full-time' } }],
};

function transportFactory(map = jobs, options = {}) {
  let calls = 0;
  return { transport: async ({ url }) => { calls += 1; if (options.failOnce && calls === 1) return { status: 503, url, data: null }; if (options.fail) return { status: 404, url, data: null }; return { status: 200, url, data: map[url] ?? { jobs: [] }, body: JSON.stringify(map[url] ?? { jobs: [] }) }; }, calls: () => calls };
}

test('Greenhouse board discovery', async () => { const result = await discoverEmployerBoards([greenhouseBoard], { transport: transportFactory().transport, retryDelayMs: 0 }); assert.equal(result.records[0].sourceType, 'GREENHOUSE'); assert.equal(result.records[0].externalId, '1'); });
test('Lever board discovery captures apply URL', async () => { const result = await discoverEmployerBoards([leverBoard], { transport: transportFactory().transport, retryDelayMs: 0 }); assert.equal(result.records[0].sourceType, 'LEVER'); assert.equal(result.records[0].applicationLink, 'https://jobs.lever.co/lever/l-1/apply'); });
test('Workday adapter consumes a configured JSON feed', async () => { const board = { company: 'Work Co', sourceType: 'WORKDAY', boardUrl: 'https://work.example/jobs' }; const result = await discoverEmployerBoards([board], { transport: transportFactory({ [board.boardUrl]: { jobPostings: [{ jobId: 'w1', title: 'Analyst', externalPath: 'https://work.example/job/w1', locations: ['Dublin'] }] } }).transport }); assert.equal(result.records[0].externalId, 'w1'); });
test('SmartRecruiters adapter consumes postings data', async () => { const board = { company: 'Smart Co', sourceType: 'SMARTRECRUITERS', boardUrl: 'https://smart.example/postings' }; const result = await discoverEmployerBoards([board], { transport: transportFactory({ [board.boardUrl]: { content: [{ id: 's1', name: 'Recruiter', ref: 'https://smart.example/job/s1', location: { city: 'Paris' } }] } }).transport }); assert.equal(result.records[0].externalId, 's1'); });
test('employer careers adapter consumes configured feed', async () => { const board = { company: 'Direct Co', sourceType: 'EMPLOYER_CAREERS', careersUrl: 'https://direct.example/careers' }; const result = await discoverEmployerBoards([board], { transport: transportFactory({ [board.careersUrl]: [{ id: 'd1', title: 'Coordinator', url: 'https://direct.example/job/d1' }] }).transport }); assert.equal(result.records[0].company, 'Direct Co'); });
test('unsupported source family is reported as board failure', async () => { const result = await discoverEmployerBoards([{ company: 'Unknown', sourceType: 'UNKNOWN', boardUrl: 'https://unknown.example' }], { transport: transportFactory().transport }); assert.equal(result.report.boardsFailed, 1); assert.equal(result.report.boardsSucceeded, 0); });
test('unavailable board is reported separately', async () => { const result = await discoverEmployerBoards([greenhouseBoard], { transport: transportFactory({}, { fail: true }).transport, retryDelayMs: 0 }); assert.equal(result.boardResults[0].status, 'FAILED'); assert.equal(result.report.boardsConfigured, result.report.boardsSucceeded + result.report.boardsFailed); });
test('transient board failure retries', async () => { const mock = transportFactory(jobs, { failOnce: true }); const result = await discoverEmployerBoards([greenhouseBoard], { transport: mock.transport, retries: 1, retryDelayMs: 0 }); assert.equal(result.records.length, 1); assert.equal(mock.calls(), 2); });
test('stable external ID and source URL are captured', () => { const result = normalizeDiscoveryRecord({ id: 99, title: 'Role', absolute_url: 'https://jobs.example/99' }, { company: 'Example', sourceType: 'EMPLOYER_CAREERS', boardId: 'example' }); assert.deepEqual({ externalId: result.externalId, sourceUrl: result.sourceUrl }, { externalId: '99', sourceUrl: 'https://jobs.example/99' }); });
test('historical external ID duplicate', async () => { const result = await discoverEmployerBoards([greenhouseBoard], { history: [{ externalId: '1' }], transport: transportFactory().transport }); assert.equal(result.report.historicalDuplicate, 1); assert.equal(result.records.length, 0); });
test('historical source URL duplicate', async () => { const result = await discoverEmployerBoards([greenhouseBoard], { history: [{ sourceUrl: 'https://boards.greenhouse.io/green/jobs/1/' }], transport: transportFactory().transport }); assert.equal(result.report.historicalDuplicate, 1); });
test('historical application URL duplicate', async () => { const result = await discoverEmployerBoards([leverBoard], { history: [{ applicationLink: 'https://jobs.lever.co/lever/l-1/apply?x=1' }], transport: transportFactory().transport }); assert.equal(result.report.historicalDuplicate, 1); });
test('normalized company/title/location match is semantic review, not destructive duplicate', async () => { const result = await discoverEmployerBoards([greenhouseBoard], { history: [{ company: 'Green-Co', title: 'Engineer', location: 'Remote' }], transport: transportFactory().transport }); assert.equal(result.report.semanticReview, 1); assert.equal(result.records.length, 0); });
test('distinct requisitions with same semantic identity are retained for review', async () => { const board = { company: 'Green Co', sourceType: 'GREENHOUSE', boardUrl: 'https://boards.example/feed' }; const map = { [board.boardUrl]: { jobs: [{ id: 1, title: 'Engineer', absolute_url: 'https://jobs.example/1', location: { name: 'Remote' } }, { id: 2, title: 'Engineer', absolute_url: 'https://jobs.example/2', location: { name: 'Remote' } }] } }; const result = await discoverEmployerBoards([board], { transport: transportFactory(map).transport }); assert.equal(result.report.acceptedNew, 1); assert.equal(result.report.semanticReview, 1); });
test('current-batch exact duplicate is classified', async () => { const board = { company: 'Green Co', sourceType: 'EMPLOYER_CAREERS', boardUrl: 'https://direct.example/feed' }; const map = { [board.boardUrl]: [{ id: '1', title: 'Engineer', url: 'https://jobs.example/1' }, { id: '1', title: 'Engineer', url: 'https://jobs.example/1' }] }; const result = await discoverEmployerBoards([board], { transport: transportFactory(map).transport }); assert.equal(result.report.currentBatchDuplicate, 1); });
test('max-records stops deterministically', async () => { const board = { company: 'Green Co', sourceType: 'EMPLOYER_CAREERS', boardUrl: 'https://direct.example/feed' }; const map = { [board.boardUrl]: [{ id: '1', title: 'A', url: 'https://jobs.example/1' }, { id: '2', title: 'B', url: 'https://jobs.example/2' }] }; const result = await discoverEmployerBoards([board], { maxRecords: 1, transport: transportFactory(map).transport }); assert.equal(result.records.length, 1); assert.equal(result.report.maxRecordsSkipped, 1); assert.equal(result.report.invariantPass, true); });
test('max-per-employer skips excess records explicitly', async () => { const board = { company: 'Green Co', sourceType: 'EMPLOYER_CAREERS', boardUrl: 'https://direct.example/feed' }; const map = { [board.boardUrl]: [{ id: '1', title: 'A', url: 'https://jobs.example/1' }, { id: '2', title: 'B', url: 'https://jobs.example/2' }] }; const result = await discoverEmployerBoards([board], { maxPerEmployer: 1, transport: transportFactory(map).transport }); assert.equal(result.records.length, 1); assert.equal(result.report.maxPerEmployerSkipped, 1); });
test('output order is deterministic despite concurrent boards', async () => { const slow = { company: 'Slow', sourceType: 'EMPLOYER_CAREERS', boardUrl: 'https://slow.example/feed' }; const fast = { company: 'Fast', sourceType: 'EMPLOYER_CAREERS', boardUrl: 'https://fast.example/feed' }; const map = { [slow.boardUrl]: [{ id: 's', title: 'Slow', url: 'https://slow.example/s' }], [fast.boardUrl]: [{ id: 'f', title: 'Fast', url: 'https://fast.example/f' }] }; const transport = async ({ url }) => { if (url.includes('slow')) await new Promise((resolve) => setTimeout(resolve, 10)); return { status: 200, url, data: map[url] }; }; const result = await discoverEmployerBoards([slow, fast], { concurrency: 2, transport }); assert.deepEqual(result.records.map((r) => r.externalId), ['s', 'f']); });
test('report accounting is derived from actual records', async () => { const result = await discoverEmployerBoards([greenhouseBoard, leverBoard], { transport: transportFactory().transport }); assert.equal(result.report.boardsConfigured, 2); assert.equal(result.report.discoveredRaw, 2); assert.equal(result.report.screened, result.report.acceptedNew + result.report.historicalDuplicate + result.report.currentBatchDuplicate + result.report.semanticReview); assert.equal(result.report.invariantPass, true); });
test('no hardcoded probe total is used', async () => { const result = await discoverEmployerBoards([], { transport: transportFactory().transport }); assert.deepEqual(result.report, { boardsConfigured: 0, boardsSucceeded: 0, boardsFailed: 0, failedBoards: [], sourceFamilyCounts: {}, discoveredRaw: 0, invalidDiscovery: 0, historicalDuplicate: 0, currentBatchDuplicate: 0, semanticReview: 0, acceptedNew: 0, acceptedForScreening: 0, screened: 0, maxRecordsSkipped: 0, maxPerEmployerSkipped: 0, perEmployerCounts: {}, invariants: { boards: true, discovered: true, screened: true }, invariantPass: true }); });
test('input board and history objects are not mutated', async () => { const board = { ...greenhouseBoard, metadata: { keep: true } }; const history = [{ externalId: 'old' }]; const before = JSON.stringify({ board, history }); await discoverEmployerBoards([board], { history, transport: transportFactory().transport }); assert.equal(JSON.stringify({ board, history }), before); });
test('aggregator URLs never become canonical records', () => { const result = normalizeDiscoveryRecord({ id: 1, title: 'Role', absolute_url: 'https://www.indeed.com/viewjob?jk=1' }, { company: 'Bad', sourceType: 'EMPLOYER_CAREERS', boardId: 'bad' }); assert.equal(result.sourceUrl, null); });
test('board configuration validation is explicit', () => { assert.deepEqual(validateBoardConfig({ company: 'x' }), ['unsupported sourceType', 'missing boardUrl, careersUrl, or boardId']); });
test('history normalization keeps exact IDs and URL noise normalized', () => { const index = normalizeHistory([{ externalId: 1, sourceUrl: 'https://jobs.example/a/?x=1' }]); assert.equal(index.ids.has('1'), true); assert.equal(index.sourceUrls.has('https://jobs.example/a'), true); });
test('semantic review does not collapse distinct source URLs', async () => { const board = { company: 'Green Co', sourceType: 'EMPLOYER_CAREERS', boardUrl: 'https://direct.example/feed' }; const map = { [board.boardUrl]: [{ id: '1', title: 'Engineer', url: 'https://jobs.example/1', location: 'Remote' }, { id: '2', title: 'Engineer', url: 'https://jobs.example/2', location: 'Remote' }] }; const result = await discoverEmployerBoards([board], { transport: transportFactory(map).transport }); assert.equal(new Set(result.screenedRecords.map((r) => r.sourceUrl)).size, 2); });
