import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { buildProvenanceSafeMigration, validateChunkSize, validateCandidate, writeProvenanceSafeMigration } from './provenance-safe-migration-builder.mjs';

const base = (id, overrides = {}) => ({ externalId: String(id), sourceUrl: `https://jobs.example.test/${id}`, applicationLink: `https://jobs.example.test/${id}/apply`, slug: `role-${id}`, title: `Role ${id}`, company: 'Example Co', description: 'Source-backed description', type: 'full-time', status: 'draft', approvalStatus: 'pending', launchEligible: false, productionDuplicateStatus: 'UNVERIFIED', ...overrides });
async function sourceFile(records, suffix = 'source') { const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'strideto-provenance-')); const file = path.join(dir, `${suffix}.json`); await fs.writeFile(file, JSON.stringify(records, null, 2), 'utf8'); return file; }
async function planFor(groups, options = {}) { const pools = []; for (const [name, records] of groups) pools.push({ sourcePool: await sourceFile(records, name), records, lineageName: name }); return buildProvenanceSafeMigration(pools, { campaignWave: 11, prefix: 'production-wave-011', preparedAt: '2026-09-07T00:00:00.000Z', ...options }); }

test('single source with one record', async () => { const plan = await planFor([['one', [base(1)]]]); assert.deepEqual(plan.manifest.lineage[0].chunkCounts, [1]); });
test('single source with ten records', async () => { const plan = await planFor([['ten', Array.from({ length: 10 }, (_, i) => base(i))]]); assert.deepEqual(plan.manifest.lineage[0].chunkCounts, [10]); });
test('single source with eleven records chunks 10 plus 1', async () => { const plan = await planFor([['eleven', Array.from({ length: 11 }, (_, i) => base(i))]]); assert.deepEqual(plan.manifest.lineage[0].chunkCounts, [10, 1]); });
test('single source with twenty-five records chunks 10 plus 10 plus 5', async () => { const plan = await planFor([['twenty-five', Array.from({ length: 25 }, (_, i) => base(i))]]); assert.deepEqual(plan.manifest.lineage[0].chunkCounts, [10, 10, 5]); });
test('multi-lineage input chunks each lineage independently', async () => { const plan = await planFor([['baseline', Array.from({ length: 12 }, (_, i) => base(`b${i}`))], ['backfill', Array.from({ length: 3 }, (_, i) => base(`f${i}`))]]); assert.deepEqual(plan.manifest.lineage.map((lineage) => lineage.chunkCounts), [[10, 2], [3]]); assert.equal(plan.manifest.lineageCount, 2); });
test('original order is preserved within each lineage', async () => { const records = [base(1), base(2), base(3)]; const plan = await planFor([['ordered', records]]); assert.equal(plan.manifest.orderPreservation, true); assert.deepEqual(plan.batches.flatMap((batch) => batch.records).map((record) => record.externalId), ['1', '2', '3']); });
test('duplicate candidate is rejected', async () => { await assert.rejects(() => planFor([['a', [base(1)]], ['b', [base(1)]]]), /Duplicate candidate identity/); });
test('candidate outside declared source membership is rejected', async () => { const candidate = base(1); const source = await sourceFile([base(2)], 'membership'); await assert.rejects(() => buildProvenanceSafeMigration([{ sourcePool: source, records: [candidate], sourceRecords: [base(2)] }], { campaignWave: 11, preparedAt: 'fixed' }), /outside declared source/); });
test('source hash is SHA-256 of exact persisted bytes', async () => { const records = [base(1)]; const file = await sourceFile(records, 'hash'); const bytes = await fs.readFile(file); const plan = await buildProvenanceSafeMigration([{ sourcePool: file, records }], { campaignWave: 11, preparedAt: 'fixed' }); assert.equal(plan.manifest.lineage[0].sourcePoolHash, crypto.createHash('sha256').update(bytes).digest('hex')); });
test('source hash changes when bytes change', async () => { const first = await sourceFile([base(1)], 'first'); const second = await sourceFile([base(1), base(2)], 'second'); const [a, b] = await Promise.all([buildProvenanceSafeMigration([{ sourcePool: first, records: [base(1)] }], { campaignWave: 11, preparedAt: 'fixed' }), buildProvenanceSafeMigration([{ sourcePool: second, records: [base(1), base(2)] }], { campaignWave: 11, preparedAt: 'fixed' })]); assert.notEqual(a.manifest.lineage[0].sourcePoolHash, b.manifest.lineage[0].sourcePoolHash); });
test('sibling report naming matches batch naming', async () => { const plan = await planFor([['source-a', [base(1)]]]); const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'strideto-output-')); const written = await writeProvenanceSafeMigration(plan, dir); assert.match(path.basename(written.batches[0].batchPath), /production-wave-011-source-a-chunk-01\.json$/); assert.match(path.basename(written.batches[0].reportPath), /production-wave-011-source-a-chunk-01-report\.json$/); });
test('sidecar report declares source pool and hash', async () => { const plan = await planFor([['source-a', [base(1)]]]); const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'strideto-output-')); const written = await writeProvenanceSafeMigration(plan, dir); const report = JSON.parse(await fs.readFile(written.batches[0].reportPath, 'utf8')); assert.equal(report.sourcePool, plan.batches[0].sourcePool); assert.equal(report.sourcePoolHash, plan.batches[0].sourcePoolHash); });
test('chunk size above ten is rejected', () => assert.throws(() => validateChunkSize(11), /between 1 and 10/));
test('chunk size zero is rejected', () => assert.throws(() => validateChunkSize(0), /between 1 and 10/));
test('missing jobType is accepted', async () => { const record = base(1); delete record.jobType; const plan = await planFor([['optional', [record]]]); assert.equal(plan.manifest.accountingInvariant, true); });
test('valid jobType is preserved', async () => { const record = base(1, { jobType: 'Private' }); const plan = await planFor([['jobtype', [record]]]); assert.equal(plan.batches[0].records[0].jobType, 'Private'); });
test('unsupported jobType is rejected', async () => { await assert.rejects(() => planFor([['bad-type', [base(1, { jobType: 'full-time' })]]]), /unsupported jobType/); });
test('UNVERIFIED production status is required', async () => { await assert.rejects(() => planFor([['bad-status', [base(1, { productionDuplicateStatus: 'VERIFIED' })]]]), /UNVERIFIED/); });
test('moderation state is preserved and validated', async () => { const record = base(1); const plan = await planFor([['moderation', [record]]]); assert.equal(plan.batches[0].records[0].status, 'draft'); assert.equal(plan.batches[0].records[0].approvalStatus, 'pending'); assert.equal(plan.batches[0].records[0].launchEligible, false); });
test('candidate content is not mutated', async () => { const records = [base(1, { responsibilities: ['Do work'], metadata: { keep: true } })]; const before = JSON.stringify(records); const plan = await planFor([['content', records]]); assert.equal(JSON.stringify(records), before); assert.deepEqual(plan.batches[0].records[0], records[0]); });
test('manifest reports no missing records', async () => { const plan = await planFor([['missing', Array.from({ length: 11 }, (_, i) => base(i))]]); assert.deepEqual(plan.manifest.missingCandidates, []); });
test('manifest reports no duplicate records across chunks', async () => { const plan = await planFor([['duplicates', Array.from({ length: 25 }, (_, i) => base(i))]]); assert.deepEqual(plan.manifest.duplicateCandidatesAcrossChunks, []); });
test('manifest accounting invariant passes', async () => { const plan = await planFor([['accounting', Array.from({ length: 11 }, (_, i) => base(i))]]); assert.equal(plan.manifest.totalCandidateCount, 11); assert.equal(plan.manifest.chunkCount, 2); assert.equal(plan.manifest.accountingInvariant, true); });
test('deterministic output with fixed preparation timestamp', async () => { const records = [base(1), base(2)]; const a = await planFor([['stable', records]], { preparedAt: 'fixed' }); const b = await planFor([['stable', records]], { preparedAt: 'fixed' }); assert.deepEqual(a.batches.map((batch) => batch.records), b.batches.map((batch) => batch.records)); assert.deepEqual(a.manifest.lineage.map((lineage) => lineage.chunkCounts), b.manifest.lineage.map((lineage) => lineage.chunkCounts)); });
test('runner-compatible sidecar fields are present', async () => { const plan = await planFor([['runner', [base(1)]]]); const report = plan.batches[0].report; for (const field of ['sourcePool', 'sourcePoolHash', 'campaignWave', 'batchNumber', 'preparedAt']) assert.ok(report[field] !== undefined); assert.equal(report.provenance, 'PASS'); });
test('legacy fallback provenance is not used', async () => { const plan = await planFor([['truthful', [base(1)]]]); assert.equal(plan.batches[0].report.sourcePool.includes('legacy'), false); assert.equal(plan.batches[0].report.sourcePool, plan.batches[0].sourcePool); });
test('multi-lineage output never declares a fake single source', async () => { const plan = await planFor([['baseline', [base('b1')]], ['backfill', [base('f1')]]]); assert.equal(new Set(plan.batches.map((batch) => batch.sourcePool)).size, 2); assert.equal(plan.manifest.accountingInvariant, true); });
test('validateCandidate reports required packaging violations', () => { assert.deepEqual(validateCandidate({}), ['missing externalId', 'missing sourceUrl', 'missing title', 'missing company', 'productionDuplicateStatus must be UNVERIFIED', 'status must be draft', 'approvalStatus must be pending', 'launchEligible must be false']); });
