/**
 * Platform Page Registry — single source of truth for public and admin pages.
 * Stable page IDs never depend on URL changes.
 */

/** @typedef {'Home'|'Jobs'|'Scholarships'|'Admissions'|'Blog'|'Career Guidance'|'Companies'|'Universities'|'Institutions'|'Foreign Studies'|'Internships'|'Webinars'|'Exam Prep'|'Tools'|'Static Pages'|'Employer'|'Student'|'Authentication'|'Admin'|'SEO'|'Public Profiles'|'Support'} PageCategory */

/**
 * @typedef {Object} PageDefinition
 * @property {string} id
 * @property {string} name
 * @property {PageCategory} category
 * @property {string} route
 * @property {boolean} dynamic
 * @property {string|null} slugResourceType
 * @property {boolean} seoEnabled
 * @property {boolean} searchable
 * @property {boolean} cmsControlled
 * @property {boolean} adCapable
 * @property {boolean} widgetCapable
 * @property {boolean} protected
 * @property {boolean} [adminOnly]
 * @property {boolean} [externalPickable]
 * @property {string[]} placements
 */

/** @type {PageDefinition[]} */
export const PAGE_REGISTRY = [
  // — Home —
  {
    id: 'home',
    name: 'Home',
    category: 'Home',
    route: '/',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: true,
    searchable: true,
    cmsControlled: true,
    adCapable: true,
    widgetCapable: true,
    protected: false,
    externalPickable: true,
    placements: ['promo-strip', 'hero', 'header-banner', 'sidebar', 'inline', 'between-sections', 'cms-section', 'footer'],
  },

  // — Jobs —
  {
    id: 'jobs-list',
    name: 'Jobs Listing',
    category: 'Jobs',
    route: '/jobs',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: true,
    searchable: true,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: true,
    protected: false,
    externalPickable: true,
    placements: ['header-banner', 'sidebar', 'inline', 'footer'],
  },
  {
    id: 'job-detail',
    name: 'Job Detail',
    category: 'Jobs',
    route: '/jobs/:slug',
    dynamic: true,
    slugResourceType: 'job',
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: ['header-banner', 'inline', 'footer'],
  },
  {
    id: 'jobs-province-landing',
    name: 'Jobs by Province',
    category: 'Jobs',
    route: '/jobs/province/:slug',
    dynamic: true,
    slugResourceType: null,
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: ['header-banner', 'sidebar', 'inline'],
  },
  {
    id: 'jobs-category-landing',
    name: 'Jobs by Category',
    category: 'Jobs',
    route: '/jobs/category/:slug',
    dynamic: true,
    slugResourceType: null,
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: ['header-banner', 'sidebar', 'inline'],
  },

  // — Scholarships —
  {
    id: 'scholarships-list',
    name: 'Scholarships Listing',
    category: 'Scholarships',
    route: '/scholarships',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: true,
    searchable: true,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: true,
    protected: false,
    externalPickable: true,
    placements: ['header-banner', 'sidebar', 'inline', 'footer'],
  },
  {
    id: 'scholarship-detail',
    name: 'Scholarship Detail',
    category: 'Scholarships',
    route: '/scholarships/:slug',
    dynamic: true,
    slugResourceType: 'scholarship',
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: ['header-banner', 'inline', 'footer'],
  },
  {
    id: 'intl-scholarships-list',
    name: 'International Scholarships',
    category: 'Scholarships',
    route: '/intl-scholarships',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: true,
    searchable: true,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: true,
    protected: false,
    externalPickable: true,
    placements: ['header-banner', 'sidebar', 'inline', 'footer'],
  },
  {
    id: 'intl-scholarship-detail',
    name: 'International Scholarship Detail',
    category: 'Scholarships',
    route: '/intl-scholarships/:id',
    dynamic: true,
    slugResourceType: 'intl-scholarship',
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: ['header-banner', 'inline'],
  },

  // — Admissions —
  {
    id: 'admissions-list',
    name: 'Admissions Listing',
    category: 'Admissions',
    route: '/admissions',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: true,
    searchable: true,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: true,
    protected: false,
    externalPickable: true,
    placements: ['header-banner', 'sidebar', 'inline', 'footer'],
  },
  {
    id: 'admission-detail',
    name: 'Admission Detail',
    category: 'Admissions',
    route: '/admissions/:slug',
    dynamic: true,
    slugResourceType: 'admission',
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: ['header-banner', 'inline', 'footer'],
  },

  // — Institutions —
  {
    id: 'institutions-list',
    name: 'Schools & Colleges',
    category: 'Institutions',
    route: '/schools-and-colleges',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: true,
    searchable: true,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: true,
    protected: false,
    externalPickable: true,
    placements: ['header-banner', 'sidebar', 'inline', 'footer'],
  },
  {
    id: 'institution-detail',
    name: 'Institution Detail',
    category: 'Institutions',
    route: '/schools-and-colleges/:slug',
    dynamic: true,
    slugResourceType: 'institution',
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: ['header-banner', 'inline'],
  },

  // — Foreign Studies —
  {
    id: 'foreign-studies-list',
    name: 'Foreign Studies',
    category: 'Foreign Studies',
    route: '/foreign-studies',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: true,
    searchable: true,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: true,
    protected: false,
    externalPickable: true,
    placements: ['header-banner', 'sidebar', 'inline', 'footer'],
  },
  {
    id: 'foreign-study-detail',
    name: 'Foreign Study Detail',
    category: 'Foreign Studies',
    route: '/foreign-studies/:slug',
    dynamic: true,
    slugResourceType: 'foreign-study',
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: ['header-banner', 'inline'],
  },

  // — Blog —
  {
    id: 'blog-list',
    name: 'Blog',
    category: 'Blog',
    route: '/blog',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: true,
    searchable: true,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: true,
    protected: false,
    externalPickable: true,
    placements: ['header-banner', 'sidebar', 'inline', 'footer'],
  },
  {
    id: 'blog-detail',
    name: 'Blog Post',
    category: 'Blog',
    route: '/blog/:slug',
    dynamic: true,
    slugResourceType: 'blog',
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: ['header-banner', 'inline', 'footer'],
  },

  // — Career Guidance —
  {
    id: 'career-guidance-list',
    name: 'Career Guidance',
    category: 'Career Guidance',
    route: '/career-guidance',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: true,
    searchable: true,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: true,
    protected: false,
    externalPickable: true,
    placements: ['header-banner', 'sidebar', 'inline', 'footer'],
  },
  {
    id: 'career-guidance-detail',
    name: 'Career Article',
    category: 'Career Guidance',
    route: '/career-guidance/:slug',
    dynamic: true,
    slugResourceType: 'career-article',
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: ['header-banner', 'inline', 'footer'],
  },

  // — Internships & Webinars —
  {
    id: 'internships-list',
    name: 'Internships',
    category: 'Internships',
    route: '/internships',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: true,
    searchable: true,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: true,
    protected: false,
    externalPickable: true,
    placements: ['header-banner', 'sidebar', 'inline', 'footer'],
  },
  {
    id: 'internship-detail',
    name: 'Internship Detail',
    category: 'Internships',
    route: '/internships/:idOrSlug',
    dynamic: true,
    slugResourceType: 'internship',
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: ['header-banner', 'inline'],
  },
  {
    id: 'webinars-list',
    name: 'Webinars',
    category: 'Webinars',
    route: '/webinars',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: true,
    searchable: true,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: true,
    protected: false,
    externalPickable: true,
    placements: ['header-banner', 'sidebar', 'inline', 'footer'],
  },

  // — Exam Prep & Tools —
  {
    id: 'exam-prep-list',
    name: 'Exam Prep',
    category: 'Exam Prep',
    route: '/exam-prep',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: true,
    searchable: true,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: true,
    protected: false,
    externalPickable: true,
    placements: ['header-banner', 'sidebar', 'inline'],
  },
  {
    id: 'exam-prep-detail',
    name: 'Exam Detail',
    category: 'Exam Prep',
    route: '/exam-prep/:slug',
    dynamic: true,
    slugResourceType: null,
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: ['header-banner', 'inline'],
  },
  {
    id: 'exam-prep-quiz',
    name: 'Exam Quiz',
    category: 'Exam Prep',
    route: '/exam-prep/quiz/:quizId',
    dynamic: true,
    slugResourceType: null,
    seoEnabled: false,
    searchable: false,
    cmsControlled: false,
    adCapable: false,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: [],
  },
  {
    id: 'resume-builder',
    name: 'Resume Builder',
    category: 'Tools',
    route: '/resume-builder',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: true,
    searchable: true,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: true,
    placements: ['header-banner', 'sidebar'],
  },
  {
    id: 'resume-analyzer',
    name: 'Resume Analyzer',
    category: 'Tools',
    route: '/resume-analyzer',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: false,
    searchable: false,
    cmsControlled: false,
    adCapable: false,
    widgetCapable: false,
    protected: true,
    externalPickable: true,
    placements: [],
  },
  {
    id: 'contact',
    name: 'Contact',
    category: 'Tools',
    route: '/contact',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: true,
    placements: ['header-banner'],
  },
  {
    id: 'submit-opportunity',
    name: 'Submit Opportunity',
    category: 'Tools',
    route: '/submit-opportunity',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: false,
    searchable: false,
    cmsControlled: false,
    adCapable: false,
    widgetCapable: false,
    protected: false,
    externalPickable: true,
    placements: [],
  },
  {
    id: 'badges',
    name: 'Badges & Leaderboard',
    category: 'Tools',
    route: '/badges',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: false,
    searchable: false,
    cmsControlled: false,
    adCapable: false,
    widgetCapable: false,
    protected: true,
    externalPickable: false,
    placements: [],
  },

  // — Public profiles —
  {
    id: 'company-profile',
    name: 'Company Profile',
    category: 'Companies',
    route: '/company/:slug',
    dynamic: true,
    slugResourceType: 'company',
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: ['header-banner', 'inline'],
  },
  {
    id: 'university-profile',
    name: 'University Profile',
    category: 'Universities',
    route: '/university/:slug',
    dynamic: true,
    slugResourceType: 'university',
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: ['header-banner', 'inline'],
  },
  {
    id: 'employer-public-profile',
    name: 'Employer Public Profile',
    category: 'Employer',
    route: '/employer/:slug',
    dynamic: true,
    slugResourceType: null,
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: false,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: [],
  },

  // — Static CMS pages —
  ...[
    ['about', 'About', '/about'],
    ['services', 'Services', '/services'],
    ['advertise', 'Advertise', '/advertise'],
    ['help-center', 'Help Center', '/help-center'],
    ['faq', 'FAQ', '/faq'],
    ['privacy-policy', 'Privacy Policy', '/privacy-policy'],
    ['terms', 'Terms', '/terms'],
    ['cookies', 'Cookies', '/cookie-policy'],
    ['disclaimer', 'Disclaimer', '/disclaimer'],
    ['refund-policy', 'Refund Policy', '/refund-policy'],
    ['careers', 'Careers', '/careers'],
    ['support', 'Support', '/support'],
  ].map(([id, name, route]) => ({
    id: `static-${id}`,
    name,
    category: 'Static Pages',
    route,
    dynamic: false,
    slugResourceType: 'cms-page',
    seoEnabled: true,
    searchable: false,
    cmsControlled: true,
    adCapable: true,
    widgetCapable: true,
    protected: false,
    externalPickable: true,
    placements: ['header-banner', 'inline', 'footer'],
  })),
  {
    id: 'support-tickets',
    name: 'Support Tickets',
    category: 'Support',
    route: '/support/tickets',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: false,
    searchable: false,
    cmsControlled: false,
    adCapable: false,
    widgetCapable: false,
    protected: false,
    externalPickable: true,
    placements: [],
  },

  // — SEO landing (grouped) —
  {
    id: 'seo-jobs-landing',
    name: 'SEO Jobs Landing',
    category: 'SEO',
    route: '/jobs-in-:slug',
    dynamic: true,
    slugResourceType: null,
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: ['header-banner', 'sidebar', 'inline'],
  },
  {
    id: 'seo-scholarships-landing',
    name: 'SEO Scholarships by Country',
    category: 'SEO',
    route: '/scholarships-in-:country',
    dynamic: true,
    slugResourceType: null,
    seoEnabled: true,
    searchable: false,
    cmsControlled: false,
    adCapable: true,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: ['header-banner', 'sidebar', 'inline'],
  },

  // — Authentication —
  ...[
    ['auth-login', 'Login', '/auth/login'],
    ['auth-register', 'Register', '/auth/register'],
    ['auth-forgot-password', 'Forgot Password', '/auth/forgot-password'],
    ['auth-reset-password', 'Reset Password', '/auth/reset-password'],
    ['auth-verify-email', 'Verify Email', '/auth/verify-email'],
    ['auth-accept-invitation', 'Accept Invitation', '/auth/accept-invitation'],
    ['employer-login', 'Employer Login', '/employer/login'],
    ['employer-register', 'Employer Register', '/employer/register'],
  ].map(([id, name, route]) => ({
    id,
    name,
    category: 'Authentication',
    route,
    dynamic: false,
    slugResourceType: null,
    seoEnabled: false,
    searchable: false,
    cmsControlled: false,
    adCapable: false,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: [],
  })),

  // — Student (protected) —
  ...[
    ['student-dashboard', 'Student Dashboard', '/dashboard'],
    ['student-profile', 'Profile', '/profile'],
    ['student-saved-jobs', 'Saved Jobs', '/saved-jobs'],
    ['student-notifications', 'Notifications', '/notifications'],
  ].map(([id, name, route]) => ({
    id,
    name,
    category: 'Student',
    route,
    dynamic: false,
    slugResourceType: null,
    seoEnabled: false,
    searchable: false,
    cmsControlled: false,
    adCapable: false,
    widgetCapable: true,
    protected: true,
    externalPickable: true,
    placements: [],
  })),

  // — Employer dashboard (protected) —
  ...[
    ['employer-dashboard', 'Employer Dashboard', '/employer'],
    ['employer-jobs', 'Employer Jobs', '/employer/jobs'],
    ['employer-post-job', 'Post Job', '/employer/jobs/new'],
    ['employer-applications', 'Applications', '/employer/applications'],
    ['employer-analytics', 'Employer Analytics', '/employer/analytics'],
    ['employer-settings', 'Employer Settings', '/employer/settings'],
  ].map(([id, name, route]) => ({
    id,
    name,
    category: 'Employer',
    route,
    dynamic: false,
    slugResourceType: null,
    seoEnabled: false,
    searchable: false,
    cmsControlled: false,
    adCapable: false,
    widgetCapable: false,
    protected: true,
    externalPickable: true,
    placements: [],
  })),

  // — Admin (optional category) —
  {
    id: 'admin-root',
    name: 'Admin Dashboard',
    category: 'Admin',
    route: '/admin',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: false,
    searchable: false,
    cmsControlled: false,
    adCapable: false,
    widgetCapable: false,
    protected: true,
    adminOnly: true,
    externalPickable: false,
    placements: [],
  },
  {
    id: 'admin-site-cms',
    name: 'Site CMS',
    category: 'Admin',
    route: '/admin/site-cms',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: false,
    searchable: false,
    cmsControlled: false,
    adCapable: false,
    widgetCapable: false,
    protected: true,
    adminOnly: true,
    externalPickable: false,
    placements: [],
  },
  {
    id: 'admin-advertisements',
    name: 'Advertisements Admin',
    category: 'Admin',
    route: '/admin/advertisements',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: false,
    searchable: false,
    cmsControlled: false,
    adCapable: false,
    widgetCapable: false,
    protected: true,
    adminOnly: true,
    externalPickable: false,
    placements: [],
  },

  // — 404 —
  {
    id: 'not-found',
    name: 'Not Found',
    category: 'Support',
    route: '*',
    dynamic: false,
    slugResourceType: null,
    seoEnabled: false,
    searchable: false,
    cmsControlled: false,
    adCapable: false,
    widgetCapable: false,
    protected: false,
    externalPickable: false,
    placements: [],
  },
];

/** Slug resource types referenced by pages (for cross-validation). */
export const REGISTRY_SLUG_RESOURCE_TYPES = [
  'job',
  'scholarship',
  'admission',
  'blog',
  'company',
  'institution',
  'webinar',
  'cms-page',
  'foreign-study',
  'internship',
  'university',
  'career-article',
  'intl-scholarship',
];

const pageById = new Map(PAGE_REGISTRY.map((p) => [p.id, p]));

export function getPageById(pageId) {
  return pageById.get(pageId) ?? null;
}

export function getPageByRoute(route) {
  return PAGE_REGISTRY.find((p) => p.route === route) ?? null;
}

export function getPagesByCategory(category) {
  return PAGE_REGISTRY.filter((p) => p.category === category);
}

export function getAdCapablePages() {
  return PAGE_REGISTRY.filter((p) => p.adCapable);
}

export function getPickablePages(options = {}) {
  const {
    includeProtected = false,
    includeAdmin = false,
    adCapableOnly = false,
  } = options;
  return PAGE_REGISTRY.filter((p) => {
    if (!includeAdmin && p.adminOnly) return false;
    if (!includeProtected && p.protected) return false;
    if (adCapableOnly && !p.adCapable) return false;
    if (p.externalPickable === false) return false;
    return Boolean(p.route) && p.route !== '*';
  });
}

export function getPageCategories(options = {}) {
  const pages = getPickablePages(options);
  return [...new Set(pages.map((p) => p.category))].sort();
}
