import mongoose from 'mongoose';
import { ProfessionalCase } from '../models/case/ProfessionalCase.js';
import { CaseApprovalRequest, CaseDocumentRequest, CaseEvent, CaseMessage, CaseNote, CaseNotificationEvent, CaseTask, CaseThread } from '../models/case/CaseRecords.js';
import { AgentMembership } from '../models/agent/AgentMembership.js';
import { Consultation } from '../models/consultation/Consultation.js';
import { VaultDocument } from '../models/vault/VaultDocument.js';
import { DocumentAccessGrant } from '../models/vault/DocumentAccessGrant.js';
import { canAccessDocument } from './vault/vaultAccessPolicy.js';
import { logAudit } from './auditService.js';
import { boundedPage, canTransitionLifecycle, canTransitionStage, CASE_OUTCOMES, CASE_TYPES, cleanCaseText, getWorkflow, HIGH_VALUE_ACTIONS, SUBMISSION_METHODS, WORKFLOW_VERSION } from '../../../shared/services/cases.js';

function fail(message, status = 400) { const error = new Error(message); error.status = status; throw error; }
function oid(value, label = 'id') { if (!mongoose.isValidObjectId(value)) fail(`Invalid ${label}`); return value; }
async function agentScope(agentAccountId) { const membership = await AgentMembership.findOne({ agentAccountId, active: true }).lean(); if (!membership) fail('Active Agent membership required', 403); return membership; }
async function caseForStudent(userId, caseId, mutable = false) { const q = ProfessionalCase.findOne({ _id: oid(caseId, 'case id'), studentUserId: userId }); const record = mutable ? await q : await q.lean(); if (!record) fail('Case not found', 404); return record; }
async function caseForAgent(agentAccountId, caseId, mutable = false) { const membership = await agentScope(agentAccountId); const q = ProfessionalCase.findOne({ _id: oid(caseId, 'case id'), organizationId: membership.organizationId, authorizedMembershipIds: membership._id }); const record = mutable ? await q : await q.lean(); if (!record) fail('Case not found', 404); return { record, membership }; }
async function event(record, eventType, actorType, actorId, metadata = {}) { return CaseEvent.create({ caseId: record._id, organizationId: record.organizationId, eventType, actorType, actorId: String(actorId), metadata }); }
async function notify(record, recipientType, recipientId, eventType) {
  const event = await CaseNotificationEvent.create({ caseId: record._id, recipientType, recipientId: String(recipientId), eventType, deliveryAttempted: false });
  if (recipientType === 'agent') {
    const { notifyAgentMembership } = await import('./agentInboxNotificationBridge.js');
    await notifyAgentMembership({
      membershipId: recipientId,
      category: 'case',
      type: eventType,
      title: 'Case update',
      body: 'A case event requires your attention. Open the case for details.',
      link: `/agent/education/cases/${record._id}`,
      dedupeKey: `agent:case:${record._id}:${eventType}:${event._id}`,
    }).catch(() => {});
  }
  if (recipientType === 'student') {
    const { createUserNotificationOnce } = await import('./notificationService.js');
    const uniqueEvent = eventType === 'case_message' || eventType === 'document_request';
    await createUserNotificationOnce({
      recipientType: 'user',
      userId: recipientId,
      category: eventType === 'case_message' ? 'message' : 'case',
      type: eventType,
      title: eventType === 'document_request' ? 'A document was requested' : 'Case update',
      body: 'A case event requires your attention. Open the case for details.',
      link: `/cases/${record._id}`,
      dedupeKey: uniqueEvent
        ? `user:case:${record._id}:${eventType}:${event._id}`
        : `user:case:${record._id}:${eventType}`,
    }).catch(() => {});
  }
  return event;
}
async function audit(record, actorType, actorId, action, metadata = {}) { return logAudit({ actor: { userId: actorId, role: actorType }, action, targetType: 'ProfessionalCase', targetId: record._id, metadata: { organizationId: String(record.organizationId), ...metadata } }); }
const safe = (record) => ({ id: String(record._id), caseType: record.caseType, workflowId: record.workflowId, workflowVersion: record.workflowVersion, lifecycle: record.lifecycle, currentStage: record.currentStage, title: record.title, summary: record.summary, destinationCountry: record.destinationCountry, assignedMembershipId: String(record.assignedMembershipId), openedAt: record.openedAt, closedAt: record.closedAt, outcome: record.outcome, processCompleted: record.processCompleted, externalResult: record.externalResult, createdAt: record.createdAt, updatedAt: record.updatedAt });

export async function proposeCase(agentAccountId, input = {}) {
  const membership = await agentScope(agentAccountId); if (!CASE_TYPES.includes(input.caseType)) fail('Unsupported case type');
  const consultation = await Consultation.findOne({ _id: oid(input.consultationId, 'consultation id'), organizationId: membership.organizationId, assignedMembershipId: membership._id, status: 'completed' }).lean();
  if (!consultation) fail('A completed, assigned consultation is required', 403);
  const workflow = getWorkflow(input.caseType, WORKFLOW_VERSION); const title = cleanCaseText(input.title, 200); if (!title) fail('Title is required');
  const record = await ProfessionalCase.create({ studentUserId: consultation.studentUserId, organizationId: membership.organizationId, assignedMembershipId: membership._id, authorizedMembershipIds: [membership._id], consultationId: consultation._id, caseType: input.caseType, workflowId: workflow.id, workflowVersion: workflow.version, lifecycle: 'awaiting_student_acceptance', currentStage: workflow.stages[0], title, summary: cleanCaseText(input.summary), destinationCountry: cleanCaseText(input.destinationCountry, 2).toUpperCase() });
  await CaseThread.create({ caseId: record._id, organizationId: record.organizationId, studentUserId: record.studentUserId, authorizedMembershipIds: [membership._id] });
  await event(record, 'case_proposed', 'agent', agentAccountId, { caseType: record.caseType, workflowVersion: record.workflowVersion }); await notify(record, 'student', record.studentUserId, 'case_proposal'); await audit(record, 'agent', agentAccountId, 'case.proposed', { caseType: record.caseType }); return safe(record);
}
export async function decideProposal(userId, caseId, input = {}) { const record = await caseForStudent(userId, caseId, true); if (record.lifecycle !== 'awaiting_student_acceptance') fail('Case proposal is no longer pending', 409); const accepted = input.decision === 'accept'; if (!accepted && input.decision !== 'reject') fail('Decision must be accept or reject'); record.lifecycle = accepted ? 'active' : 'cancelled'; record.openedAt = accepted ? new Date() : null; record.closedAt = accepted ? null : new Date(); if (!accepted) record.outcome = 'cancelled'; await record.save(); if (accepted) { const { recordHandoffConsent, CONSENT_PURPOSES } = await import('./consentGrantService.js'); await recordHandoffConsent({ subjectId: userId, counterpartyId: record.organizationId, counterpartyType: 'agent', purpose: CONSENT_PURPOSES.AGENT_CASE, resourceScope: `case:${record._id}`, grantedAt: new Date(), provenance: 'student_case_accept', auditIdentity: `case:${record._id}` }); } await event(record, accepted ? 'student_accepted' : 'student_rejected', 'student', userId); await notify(record, 'agent', record.assignedMembershipId, 'case_proposal_response'); await audit(record, 'student', userId, accepted ? 'case.accepted' : 'case.rejected'); return safe(record); }
export async function listCases(actorType, actorId, query = {}) { const { page, limit, skip } = boundedPage(query); let filter; if (actorType === 'student') filter = { studentUserId: actorId }; else { const membership = await agentScope(actorId); filter = { organizationId: membership.organizationId, authorizedMembershipIds: membership._id }; } if (query.lifecycle) filter.lifecycle = query.lifecycle; const term = String(query.q || '').trim().slice(0, 80); if (term) filter.title = { $regex: term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), $options: 'i' }; const [rows,total] = await Promise.all([ProfessionalCase.find(filter).sort({ updatedAt: -1 }).skip(skip).limit(limit).lean(), ProfessionalCase.countDocuments(filter)]); return { cases: rows.map(safe), page, limit, total }; }
export async function getCase(actorType, actorId, caseId) { const record = actorType === 'student' ? await caseForStudent(actorId, caseId) : (await caseForAgent(actorId, caseId)).record; const [timeline, notes, approvals, tasks, documents, thread] = await Promise.all([CaseEvent.find({ caseId: record._id }).sort({ createdAt: 1 }).lean(), CaseNote.find({ caseId: record._id, ...(actorType === 'student' ? { visibility: 'shared' } : {}) }).sort({ createdAt: -1 }).lean(), CaseApprovalRequest.find({ caseId: record._id }).sort({ createdAt: -1 }).lean(), CaseTask.find({ caseId: record._id }).sort({ createdAt: -1 }).lean(), CaseDocumentRequest.find({ caseId: record._id }).sort({ createdAt: -1 }).lean(), CaseThread.findOne({ caseId: record._id }).lean()]); return { case: safe(record), workflow: getWorkflow(record.caseType, record.workflowVersion), timeline, notes, approvals, tasks, documentRequests: documents, threadId: thread ? String(thread._id) : null }; }
export async function transitionStage(agentAccountId, caseId, input = {}) { const { record } = await caseForAgent(agentAccountId, caseId, true); if (record.lifecycle !== 'active') fail('Only active cases can progress', 409); if (!canTransitionStage(record.caseType, record.workflowVersion, record.currentStage, input.stage)) fail('Invalid workflow stage transition', 409); if (input.stage === 'submitted_external') { const approved = await CaseApprovalRequest.exists({ caseId: record._id, actionType: 'external_submission', status: 'approved' }); if (!approved) fail('Student approval is required before recording external submission', 409); if (!SUBMISSION_METHODS.includes(input.submissionMethod) || input.submissionMethod === 'authorized_integration_future') fail('A truthful current submission method is required'); } const from = record.currentStage; record.currentStage = input.stage; await record.save(); await event(record, 'stage_changed', 'agent', agentAccountId, { from, to: input.stage, ...(input.stage === 'submitted_external' ? { submissionMethod: input.submissionMethod, submittedByStrideto: false } : {}) }); await notify(record, 'student', record.studentUserId, 'stage_change'); await audit(record, 'agent', agentAccountId, 'case.stage_changed', { from, to: input.stage }); return safe(record); }
export async function transitionLifecycle(actorType, actorId, caseId, input = {}) { const record = actorType === 'student' ? await caseForStudent(actorId, caseId, true) : (await caseForAgent(actorId, caseId, true)).record; if (!canTransitionLifecycle(record.lifecycle, input.lifecycle)) fail('Invalid case lifecycle transition', 409); if (actorType === 'agent' && ['completed','transferred'].includes(input.lifecycle)) { const type = input.lifecycle === 'transferred' ? 'agent_transfer' : 'case_closure'; if (!await CaseApprovalRequest.exists({ caseId: record._id, actionType: type, status: 'approved' })) fail('Student approval is required', 409); } const from = record.lifecycle; record.lifecycle = input.lifecycle; if (['completed','cancelled','transferred'].includes(input.lifecycle)) { record.closedAt = new Date(); record.processCompleted = input.lifecycle === 'completed'; if (input.lifecycle !== 'completed') record.outcome = input.lifecycle === 'transferred' ? 'transferred' : (input.outcome || 'cancelled'); await CaseThread.updateOne({ caseId: record._id }, { $set: { status: 'read_only' } }); } await record.save(); await event(record, `case_${input.lifecycle}`, actorType, actorId, { from, to: input.lifecycle }); await audit(record, actorType, actorId, `case.${input.lifecycle}`, { from }); return safe(record); }
export async function addNote(agentAccountId, caseId, input = {}) { const { record, membership } = await caseForAgent(agentAccountId, caseId); const body = cleanCaseText(input.body, 4000); if (!body || !['shared','agent_private'].includes(input.visibility)) fail('Valid note and visibility required'); const note = await CaseNote.create({ caseId: record._id, authorMembershipId: membership._id, visibility: input.visibility, body }); if (input.visibility === 'shared') await event(record, 'shared_note_added', 'agent', agentAccountId, { noteId: String(note._id) }); await audit(record, 'agent', agentAccountId, 'case.note_added', { visibility: input.visibility }); return note; }
export async function requestApproval(agentAccountId, caseId, input = {}) { const { record, membership } = await caseForAgent(agentAccountId, caseId); if (!HIGH_VALUE_ACTIONS.includes(input.actionType)) fail('Unsupported approval action'); const explanation = cleanCaseText(input.explanation); if (!explanation) fail('Explanation required'); const approval = await CaseApprovalRequest.create({ caseId: record._id, actionType: input.actionType, requestedByMembershipId: membership._id, explanation, proposedAction: input.proposedAction || {}, expiresAt: input.expiresAt || null }); await event(record, 'student_approval_requested', 'agent', agentAccountId, { approvalId: String(approval._id), actionType: approval.actionType }); await notify(record, 'student', record.studentUserId, 'student_approval_request'); await audit(record, 'agent', agentAccountId, 'case.approval_requested', { actionType: approval.actionType }); return approval; }
export async function decideApproval(userId, caseId, approvalId, input = {}) { const record = await caseForStudent(userId, caseId); if (!['approve','reject'].includes(input.decision)) fail('Decision must be approve or reject'); const approval = await CaseApprovalRequest.findOneAndUpdate({ _id: oid(approvalId, 'approval id'), caseId: record._id, status: 'pending', $or: [{ expiresAt: null }, { expiresAt: { $gt: new Date() } }] }, { $set: { status: input.decision === 'approve' ? 'approved' : 'rejected', respondedAt: new Date(), studentComment: cleanCaseText(input.comment, 1000) } }, { new: true }).lean(); if (!approval) fail('Approval request is unavailable', 409); await event(record, `student_${approval.status}`, 'student', userId, { approvalId: String(approval._id), actionType: approval.actionType }); await notify(record, 'agent', record.assignedMembershipId, 'approval_response'); await audit(record, 'student', userId, `case.approval_${approval.status}`, { actionType: approval.actionType }); return approval; }
export async function createTask(agentAccountId, caseId, input = {}) { const { record, membership } = await caseForAgent(agentAccountId, caseId); const title = cleanCaseText(input.title, 200); if (!title || !['student','agent'].includes(input.responsibleActor)) fail('Valid task required'); const task = await CaseTask.create({ caseId: record._id, title, responsibleActor: input.responsibleActor, responsibleMembershipId: input.responsibleActor === 'agent' ? membership._id : null, dueAt: input.dueAt || null, requirementRef: cleanCaseText(input.requirementRef,150), source: 'agent' }); await event(record, 'checklist_item_created', 'agent', agentAccountId, { taskId: String(task._id), responsibleActor: task.responsibleActor }); return task; }
export async function completeTask(actorType, actorId, caseId, taskId) { const record = actorType === 'student' ? await caseForStudent(actorId, caseId) : (await caseForAgent(actorId, caseId)).record; const filter = { _id: oid(taskId,'task id'), caseId: record._id, status: { $in: ['pending','in_progress'] }, responsibleActor: actorType }; const task = await CaseTask.findOneAndUpdate(filter, { $set: { status: 'completed' } }, { new: true }).lean(); if (!task) fail('Task not found or not owned by actor', 404); await event(record, 'checklist_item_completed', actorType, actorId, { taskId: String(task._id) }); return task; }
export async function requestDocument(agentAccountId, caseId, input = {}) { const { record, membership } = await caseForAgent(agentAccountId, caseId); const documentType = cleanCaseText(input.documentType,100), purpose = cleanCaseText(input.purpose,500); if (!documentType || !purpose) fail('Document type and purpose required'); const request = await CaseDocumentRequest.create({ caseId: record._id, documentType, purpose, requestedByMembershipId: membership._id, dueAt: input.dueAt || null, requirementRef: cleanCaseText(input.requirementRef,150) }); await event(record, 'document_requested', 'agent', agentAccountId, { requestId: String(request._id), documentType }); await notify(record, 'student', record.studentUserId, 'document_request'); await audit(record, 'agent', agentAccountId, 'case.document_requested', { documentType }); return request; }
export async function shareDocument(userId, caseId, requestId, input = {}) { const record = await caseForStudent(userId, caseId); const request = await CaseDocumentRequest.findOne({ _id: oid(requestId,'request id'), caseId: record._id }); if (!request) fail('Document request not found',404); const [document,grant] = await Promise.all([VaultDocument.findOne({ _id: oid(input.documentId,'document id'), ownerUserId: userId }).lean(), DocumentAccessGrant.findOne({ _id: oid(input.grantId,'grant id'), ownerUserId: userId, documentId: input.documentId, granteeType: 'agent', granteeId: String(record.assignedMembershipId), caseRef: String(record._id), status: 'active', revokedAt: null, permissions: 'view', $or: [{ expiresAt: null }, { expiresAt: { $gt: new Date() } }] }).lean()]); if (!document || !grant) fail('An exact active case-scoped Vault grant is required',403); request.vaultDocumentId = document._id; request.grantId = grant._id; request.status = 'shared'; request.fulfilledAt = new Date(); await request.save(); await event(record, 'document_shared', 'student', userId, { requestId: String(request._id), documentId: String(document._id), grantId: String(grant._id) }); await audit(record,'student',userId,'case.document_shared',{ documentId: String(document._id), grantId: String(grant._id) }); return request; }
export async function resolveCaseDocument(agentAccountId, caseId, requestId) { const { record, membership } = await caseForAgent(agentAccountId, caseId); const request = await CaseDocumentRequest.findOne({ _id: oid(requestId,'request id'), caseId: record._id, status: 'shared' }).lean(); if (!request) fail('Shared document not found',404); const document = await VaultDocument.findById(request.vaultDocumentId).lean(); const access = await canAccessDocument({ actor: { type: 'agent', id: String(membership._id) }, document, grantId: String(request.grantId), requiredPermission: 'view' }); if (!access.allowed) fail('Vault access denied',403); const grant = await DocumentAccessGrant.findById(request.grantId).lean(); if (grant.caseRef !== String(record._id)) fail('Vault case scope mismatch',403); return { documentId: String(document._id), name: document.displayName || document.title || 'Document', access: 'granted' }; }
export async function listMessages(actorType, actorId, caseId, query={}) { const record = actorType === 'student' ? await caseForStudent(actorId,caseId) : (await caseForAgent(actorId,caseId)).record; const thread = await CaseThread.findOne({ caseId: record._id }).lean(); const { page,limit,skip }=boundedPage(query); const [messages,total]=await Promise.all([CaseMessage.find({threadId:thread._id}).sort({createdAt:-1}).skip(skip).limit(limit).lean(),CaseMessage.countDocuments({threadId:thread._id})]); return {messages,page,limit,total}; }
export async function sendMessage(actorType, actorId, caseId, input={}) { const record = actorType === 'student' ? await caseForStudent(actorId,caseId) : (await caseForAgent(actorId,caseId)).record; const thread=await CaseThread.findOne({caseId:record._id,status:'open'}).lean(); if(!thread) fail('Case messaging is closed',409); const text=cleanCaseText(input.text,4000); if(!text) fail('Message required'); const message=await CaseMessage.create({threadId:thread._id,senderActorType:actorType,senderId:String(actorId),text}); await notify(record,actorType==='student'?'agent':'student',actorType==='student'?record.assignedMembershipId:record.studentUserId,'case_message'); await audit(record,actorType,actorId,'case.message_created',{messageType:'text'}); return message; }
export async function recordOutcome(agentAccountId,caseId,input={}) { const {record}=await caseForAgent(agentAccountId,caseId,true); if(!CASE_OUTCOMES.includes(input.outcome)) fail('Invalid outcome'); record.outcome=input.outcome; record.externalResult=cleanCaseText(input.externalResult,200); await record.save(); await event(record,'outcome_recorded','agent',agentAccountId,{outcome:record.outcome,processCompleted:record.processCompleted}); return safe(record); }
export async function executeTransfer(agentAccountId,caseId,input={}) { const {record}=await caseForAgent(agentAccountId,caseId,true); const target=await AgentMembership.findOne({_id:oid(input.membershipId,'membership id'),organizationId:record.organizationId,active:true}).lean(); if(!target) fail('Active same-organization membership required',403); const approval=await CaseApprovalRequest.findOne({caseId:record._id,actionType:'agent_transfer',status:'approved','proposedAction.membershipId':String(target._id)}).lean(); if(!approval) fail('Exact Student-approved transfer required',409); const old=record.assignedMembershipId; record.assignedMembershipId=target._id; record.authorizedMembershipIds=[target._id]; await record.save(); await CaseThread.updateOne({caseId:record._id},{$set:{authorizedMembershipIds:[target._id]}}); await event(record,'agent_reassigned','agent',agentAccountId,{fromMembershipId:String(old),toMembershipId:String(target._id),vaultGrantsTransferred:false,privateNotesTransferred:false}); await notify(record,'student',record.studentUserId,'agent_reassignment'); await audit(record,'agent',agentAccountId,'case.agent_reassigned',{fromMembershipId:String(old),toMembershipId:String(target._id)}); return safe(record); }
