import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { agentPublicApi } from '../../services/agentService';
import { ROUTES } from '../../constants';

export default function AgentDirectory() {
  const [filters, setFilters] = useState({ agentType: '', countryCode: '', destinationCountry: '' });
  const [result, setResult] = useState({ profiles: [], total: 0, page: 1, pages: 0 });
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = (page = 1) => { setLoading(true); setError(''); const params = Object.fromEntries(Object.entries({ ...filters, page, limit: 20 }).filter(([, value]) => value !== '')); return agentPublicApi.getDirectory(params).then(({ data }) => setResult(data)).catch(() => setError('Unable to load the agent directory.')).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  return <div className="mx-auto max-w-6xl px-4 py-10"><div><h1 className="text-3xl font-semibold text-slate-900">Verified agents and agencies</h1><p className="mt-2 text-slate-600">Only organizations with current approved verification appear here.</p></div>
    <form onSubmit={(event) => { event.preventDefault(); load(); }} className="mt-6 grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-4"><select value={filters.agentType} onChange={(e) => setFilters((f) => ({ ...f, agentType: e.target.value }))} className="rounded-lg border p-2"><option value="">All types</option><option value="agent">Agent</option><option value="agency">Agency</option></select><input value={filters.countryCode} onChange={(e) => setFilters((f) => ({ ...f, countryCode: e.target.value.toUpperCase() }))} maxLength="2" placeholder="Country code" className="rounded-lg border p-2" /><input value={filters.destinationCountry} onChange={(e) => setFilters((f) => ({ ...f, destinationCountry: e.target.value.toUpperCase() }))} maxLength="2" placeholder="Destination code" className="rounded-lg border p-2" /><button className="rounded-lg bg-blue-700 px-4 py-2 text-white">Filter</button></form>
    {error && <p className="mt-5 rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}{loading ? <p className="mt-8 text-slate-500">Loading directory…</p> : result.profiles.length === 0 ? <p className="mt-8 rounded-xl border bg-white p-6 text-slate-500">No approved profiles match these filters.</p> : <div className="mt-8 grid gap-4 md:grid-cols-2">{result.profiles.map((profile) => <Link key={profile.slug} to={`${ROUTES.AGENT_PUBLIC_DIRECTORY}/${profile.slug}`} className="rounded-xl border bg-white p-5 transition hover:border-blue-300"><div className="flex justify-between gap-3"><h2 className="font-semibold text-slate-900">{profile.professionalName}</h2><span className="text-xs uppercase text-slate-500">{profile.agentType}</span></div><p className="mt-2 line-clamp-3 text-sm text-slate-600">{profile.professionalSummary || 'Professional profile'}</p><p className="mt-3 text-xs text-slate-500">{profile.countryCode} · {(profile.languages || []).join(', ')}</p></Link>)}</div>}
    {result.pages > 1 && <div className="mt-6 flex items-center justify-center gap-3"><button disabled={result.page <= 1 || loading} onClick={() => load(result.page - 1)} className="rounded border px-3 py-2 disabled:opacity-40">Previous</button><span className="text-sm">Page {result.page} of {result.pages}</span><button disabled={result.page >= result.pages || loading} onClick={() => load(result.page + 1)} className="rounded border px-3 py-2 disabled:opacity-40">Next</button></div>}
  </div>;
}
