import { useEffect,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { agentPublicApi,studentMarketplaceApi } from '../../services/agentService';
import { checkSaved,saveOpportunity,unsaveOpportunity } from '../../services/actionEngineService';
import { ROUTES } from '../../constants';
export default function AgentMarketplaceDetail(){const {t}=useTranslation('common');const {slug}=useParams();const [post,setPost]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [message,setMessage]=useState('');const [saved,setSaved]=useState(false);const [busy,setBusy]=useState(false);useEffect(()=>{agentPublicApi.getMarketplacePost(slug).then(r=>{setPost(r.data.post);return checkSaved('agent_marketplace_post',r.data.post.id).then(x=>setSaved(!!x.saved)).catch(()=>{});}).catch(e=>setError(e.response?.status===404?'This marketplace post is not currently available.':'Unable to load post.')).finally(()=>setLoading(false));},[slug]);const interest=async()=>{setBusy(true);setError('');try{await studentMarketplaceApi.expressInterest(slug);setMessage('Interest recorded. The Agent receives only a minimal relationship record.');}catch(e){setError(e.response?.data?.error||'Sign in as a Student to request information.');}finally{setBusy(false);}};const toggleSave=async()=>{setBusy(true);setError('');try{if(saved)await unsaveOpportunity('agent_marketplace_post',post.id);else await saveOpportunity({entityType:'agent_marketplace_post',entityId:post.id});setSaved(!saved);setMessage(saved?'Removed from saved items.':'Saved privately. No Agent relationship was created.');}catch{setError('Sign in as a Student to save this item.');}finally{setBusy(false);}};
if(loading)return <div className="mx-auto max-w-4xl p-8">{t('loading',{defaultValue:'Loading…'})}</div>;if(error&&!post)return <div className="mx-auto max-w-4xl p-8"><p className="rounded bg-amber-50 p-4 text-amber-800">{error}</p></div>;return <div className="mx-auto max-w-4xl space-y-6 px-4 py-10"><Link to={ROUTES.AGENT_PUBLIC_MARKETPLACE} className="text-sm text-blue-700">← Marketplace</Link>{error&&<p className="rounded bg-red-50 p-3 text-red-700">{error}</p>}{message&&<p className="rounded bg-green-50 p-3 text-green-700">{message}</p>}<header className="rounded-xl border bg-white p-6"><p className="text-xs uppercase text-blue-700">{post.postType.replaceAll('_',' ')}</p><h1 className="mt-2 text-3xl font-semibold">{post.title}</h1><p className="mt-3 text-slate-600">{post.summary}</p><div className="mt-4 flex flex-wrap gap-2">{post.trustBadges.map(b=><span key={b} className="rounded-full bg-green-50 px-2 py-1 text-xs text-green-800">{b.replaceAll('_',' ')}</span>)}</div><p className="mt-4 text-sm">By <Link to={`/agents/${post.agent.slug}`} className="text-blue-700">{post.agent.professionalName}</Link></p></header>
<section className="rounded-xl border-l-4 border-blue-500 bg-blue-50 p-5"><p className="text-xs font-bold uppercase text-blue-800">Agent / Agency statement</p><p className="mt-2 whitespace-pre-line text-slate-800">{post.agentStatement}</p></section>
{post.canonicalReferences.length>0&&<section className="rounded-xl border-l-4 border-green-600 bg-white p-5"><p className="text-xs font-bold uppercase text-green-800">Official / source-backed facts</p><div className="mt-3 space-y-3">{post.canonicalReferences.map((ref,i)=><div key={`${ref.referenceType}-${i}`}><p className="font-medium">{ref.name||ref.title||ref.officialName}</p><p className="text-xs text-slate-500">Canonical {ref.referenceType.replaceAll('_',' ')} record</p></div>)}{post.factualClaims.map(c=><p key={c.claimKey} className="text-sm text-slate-700">{c.statement}</p>)}</div>{post.sources.map(s=><a key={s._id} href={s.url} target="_blank" rel="noreferrer" className="mt-3 block text-sm text-blue-700">Source: {s.label||s.publisher||'Official reference'} · Last verified {s.lastVerifiedAt?new Date(s.lastVerifiedAt).toLocaleDateString():'unknown'}</a>)}{post.freshnessWarning&&<p className="mt-3 rounded bg-amber-50 p-2 text-sm text-amber-800">{post.freshnessWarning}</p>}</section>}
{post.relatedService&&<section className="rounded-xl border bg-white p-5"><p className="text-xs font-bold uppercase text-slate-500">Related professional service</p><h2 className="mt-1 font-semibold">{post.relatedService.title}</h2><p className="mt-2 text-sm text-slate-600">{post.relatedService.deliveryMode} · {post.relatedService.pricingMode.replaceAll('_',' ')}</p><Link to={`/consultations/new?serviceId=${post.relatedService._id}&marketplacePostId=${post.id}`} className="mt-4 inline-block rounded bg-blue-700 px-4 py-2 text-sm text-white">Request consultation</Link></section>}
<section className="rounded-xl border-l-4 border-slate-500 bg-slate-50 p-5"><p className="text-xs font-bold uppercase">Strideto platform information</p><p className="mt-2 text-sm text-slate-700">{post.platformInformation}</p></section><div className="flex flex-wrap gap-3"><button disabled={busy} onClick={interest} className="rounded bg-blue-700 px-4 py-2 text-white disabled:opacity-50">I’m interested — request information</button><button disabled={busy} onClick={toggleSave} className="rounded border px-4 py-2 disabled:opacity-50">{saved?'Remove saved item':'Save privately'}</button></div><p className="text-xs text-slate-500">Requesting information does not share your full profile or Vault documents and does not open messaging or booking.</p></div>}
