import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { agentPublicApi } from '../../services/agentService';
import { ROUTES } from '../../constants';

export default function AgentPublicProfile() {
  const { slug } = useParams(); const [profile, setProfile] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { agentPublicApi.getProfile(slug).then(({ data }) => setProfile(data.profile)).catch((err) => setError(err.response?.status === 404 ? 'This profile is not publicly available.' : 'Unable to load this profile.')).finally(() => setLoading(false)); }, [slug]);
  if (loading) return <div className="mx-auto max-w-4xl px-4 py-10 text-slate-500">Loading profile…</div>;
  if (error) return <div className="mx-auto max-w-4xl px-4 py-10"><p className="rounded-lg bg-amber-50 p-4 text-amber-800">{error}</p><Link to={ROUTES.AGENT_PUBLIC_DIRECTORY} className="mt-4 inline-block text-blue-700">Back to directory</Link></div>;
  return <div className="mx-auto max-w-4xl space-y-6 px-4 py-10"><Link to={ROUTES.AGENT_PUBLIC_DIRECTORY} className="text-sm text-blue-700">← Agent directory</Link><header className="rounded-xl border bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-wide text-blue-700">Approved {profile.agentType}</p><h1 className="mt-1 text-3xl font-semibold">{profile.professionalName}</h1><p className="mt-2 text-sm text-slate-500">{profile.countryCode}{profile.officeLocation?.city ? ` · ${profile.officeLocation.city}` : ''}</p></div><div className="flex flex-wrap gap-2">{profile.trustBadges.map((badge) => <span key={badge} className="rounded-full bg-green-50 px-3 py-1 text-xs text-green-800">{badge.replaceAll('_', ' ')}</span>)}</div></div><p className="mt-5 whitespace-pre-line text-slate-700">{profile.professionalSummary}</p>{profile.website && <a href={profile.website} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm text-blue-700">Visit professional website</a>}</header>
    <section className="grid gap-4 rounded-xl border bg-white p-6 sm:grid-cols-2"><div><h2 className="font-semibold">Languages</h2><p className="mt-1 text-sm text-slate-600">{profile.languages.join(', ') || 'Not provided'}</p></div><div><h2 className="font-semibold">Destination countries</h2><p className="mt-1 text-sm text-slate-600">{profile.destinationCountries.join(', ') || 'Not provided'}</p></div><div className="sm:col-span-2"><h2 className="font-semibold">Specialties</h2><p className="mt-1 text-sm text-slate-600">{profile.specialties.join(', ') || 'Not provided'}</p></div></section>
    <section><h2 className="text-xl font-semibold">Active services</h2>{profile.services.length === 0 ? <p className="mt-3 rounded-xl border bg-white p-5 text-sm text-slate-500">No active services published.</p> : <div className="mt-3 grid gap-4 sm:grid-cols-2">{profile.services.map((service) => <article key={service._id} className="rounded-xl border bg-white p-5"><h3 className="font-medium">{service.title}</h3><p className="mt-2 text-sm text-slate-600">{service.description}</p><p className="mt-3 text-xs text-slate-500">{service.deliveryMode} · {service.pricingMode.replaceAll('_', ' ')}</p></article>)}</div>}</section><p className="text-xs text-slate-500">Badges describe accepted evidence only. Strideto does not guarantee outcomes or endorse self-declared claims.</p></div>;
}
